import React, { useMemo, useState } from "react";
import "./Shoes.css";
// IMPORT the hero image from your src tree so the bundler resolves it correctly.
// Adjust the path if your image is in a different folder under src.
import ShoesHero from "../assets/images/dashboard/Commodities.png";

/**
 * Commodities page (kept layout & CSS identical to Shoes.jsx)
 * - Uses the same Shoes.css styles and the same two-column, 8-per-page layout.
 * - Product URLs updated per your request (commodities list).
 * - Only product URLs and hero image changed; rest of the file left intact.
 */

/* Helper: build a friendly name from the Cloudinary filename */
function friendlyNameFromUrl(url) {
  try {
    const parts = url.split("/");
    let name = parts[parts.length - 1] || url;
    // remove extension
    name = name.replace(/\.[a-zA-Z0-9]+$/, "");
    // remove trailing numeric groups like _93_53 or _142_99 etc.
    name = name.replace(/(_\d+){1,3}$/, "");
    // replace underscores and multiple spaces with single space
    name = name.replace(/[_]+/g, " ").replace(/\s{2,}/g, " ").trim();
    if (name.length > 70) return name.slice(0, 67) + "...";
    return decodeURIComponent(name);
  } catch {
    return url;
  }
}

/* Furniture product URLs replaced with Commodities URLs provided by you */
const productUrls = [
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094428/products/Electric_Mini_Smart_Car_Electric_Four-wheeler_New_Energy_Hom_Electric_Mini_Smart_Car_Electric_Four-wheeler_New_Energy_Hom_3069.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094422/products/Electric_Hot_Water_Boiler_for_Bathroom_Smart_Kitchen_Applian_Electric_Hot_Water_Boiler_for_Bathroom_Smart_Kitchen_Applian_625_2.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094414/products/Electric_Cooking_Home_Machine_And_Cooking_Pot_Making_Machine_Electric_Cooking_Home_Machine_And_Cooking_Pot_Making_Machine_527_99.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094418/products/Electric_Flour_Mixer_For_Cuisine_Robot_1500w_Bakery_Dough_Ho_Electric_Flour_Mixer_For_Cuisine_Robot_1500w_Bakery_Dough_Ho_506.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094440/products/Electric_patient_lifts_adjustable_hospital_chair_lifting_hea_Electric_patient_lifts_adjustable_hospital_chair_lifting_hea_541_97.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094436/products/Electric_Stainless_Steel_Wheat_Flour_Milling_Machine_Wet_And_Electric_Stainless_Steel_Wheat_Flour_Milling_Machine_Wet_And_430_1.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119265/products/Outdoor_portable_power_station_2000W_for_EV_auto_car_Electri_Outdoor_portable_power_station_2000W_for_EV_auto_car_Electri_968.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092967/products/Built-in_electric_ovens_household_oven_pizza_oven_electric_o_Built-in_electric_ovens_household_oven_pizza_oven_electric_o_487_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120711/products/Window_cleaner_electric_glass_limpiacristales_remote_control_Window_cleaner_electric_glass_limpiacristales_remote_control_165.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091419/products/45L_wholesale_electric_appliance_industrial_pressure_cooker_45L_wholesale_electric_appliance_industrial_pressure_cooker_528.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119470/products/Professional_Commercial_Kitchen_Equipment_Industrial_Electri_We_are_a_leading_marketing_agency_that_utilIZES_over_10_year_Professional_Commercial_Kitchen_Equipment_Industrial_Electri.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091652/products/65L_Built_In_Electric_Ovens_65L_Built_In_Electric_Ovens_65L_Built_In_Electric_Ovens_286.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117913/products/Medical_Supplies_Wheelchair_Handicapped_Steel_Electric_Wheel_Medical_Supplies_Wheelchair_Handicapped_Steel_Electric_Wheel_360.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120253/products/Water_heater_price_for_shower_electrical_storage_blue_enamel_Water_heater_price_for_shower_electrical_storage_blue_enamel_513_6.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118362/products/Multifunction_Elderly_Electric_Patient_Handicap_Lifting_Equi_Multifunction_Elderly_Electric_Patient_Handicap_Lifting_Equi_572.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093235/products/Chefmax_Commercial_Intelligent_Automatic_Cooker_Electric_Ene_Chefmax_Commercial_Intelligent_Automatic_Cooker_Electric_Ene_1040.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117226/products/Lightweight_Aluminum_Alloy_Manual_Electric_Power_Wheelchair_Lightweight_Aluminum_Alloy_Manual_Electric_Power_Wheelchair_696.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093012/products/CNTECH_Factory_2600W_Multifunction_Electric_Carpet_Mattress_CNTECH_Factory_2600W_Multifunction_Electric_Carpet_Mattress_239_8.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096106/products/High_Quality_Electromagnetic_Oven_Electric_Appliance_Inducti_High_Quality_Electromagnetic_Oven_Electric_Appliance_Inducti_1219_4.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094447/products/Electronic_Adult_Wheelchair_Disability_Electric_Wheelchair_R_Electronic_Adult_Wheelchair_Disability_Electric_Wheelchair_R_364.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118550/products/New_Designs_Commercial_Coffee_Machine_Electric_Appliance_New_New_Designs_Commercial_Coffee_Machine_Electric_Appliance_562_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120692/products/Wholesales_boneng_electric_appliance_belt_drive_ebike_72v150_Wholesales_boneng_electric_appliance_belt_drive_ebike_72v150_1573.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117917/products/Medical_Used_Portable_Electric_Stair_Climbing_Wheelchair_for_Medical_Used_Portable_Electric_Stair_Climbing_Wheelchair_for_3300.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096321/products/High_Thermal_Efficiency_3_Burner_Commercial_Electric_Inducti_High_Thermal_Efficiency_3_Burner_Commercial_Electric_Inducti_618.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750089991/products/110V_household_electric_multifunction_smart_food_processor_1_110V_household_electric_multifunction_smart_food_processor_548_9.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118505/products/New_Carbon_Fiber_Disabled_Powerful_Electric_Automatic_Wheelc_New_Carbon_Fiber_Disabled_Powerful_Electric_Automatic_Wheelc_1155.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117917/products/Medical_Used_Portable_Electric_Stair_Climbing_Wheelchair_for_Medical_Used_Portable_Electric_Stair_Climbing_Wheelchair_for_3300.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117930/products/Medical_health_device_adjustable_foldable_electric_power_wid_Medical_health_device_adjustable_foldable_electric_power_wid_3300.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092550/products/Bathroom_Electric_Toilet_Lift_health_care_supplies_products_Bathroom_Electric_Toilet_Lift_health_care_supplies_products_755_64.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121272/products/miniPro_China_follow_electric_balance_scooter_mope_miniPro_C_miniPro_China_follow_electric_balance_scooter_mope_389_4.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117933/products/Medical_motorised_wheelchair_with_electric_and_manual_model_Medical_motorised_wheelchair_with_electric_and_manual_model_660.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120493/products/Wholesale_Manufacturer_3_Burner_Electric_Induction_Cooker_Bu_Wholesale_Manufacturer_3_Burner_Electric_Induction_Cooker_Bu_91_3.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094754/products/Factory_Wholesale_Smart_Office_Table_Electric_Desk_Standing_Factory_Wholesale_Smart_Office_Table_Electric_Desk_Standing_435_6.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092086/products/Aluminum_Alloy_Easy_Folding_Joystick_Controller_Electric_Pow_Aluminum_Alloy_Easy_Folding_Joystick_Controller_Electric_Pow_650.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120455/products/Wholesale_High_Quality_Cheap_Electric_Commercial_Automatic_E_Wholesale_High_Quality_Cheap_Electric_Commercial_Automatic_E_623_75.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121568/products/wholesale_factory_price_electric_central_heating_boiler_floo_wholesale_factory_price_electric_central_heating_boiler_floo_329_45.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121231/products/medical_portable_electric_wheelchair_toilet_move_wheel_nursi_medical_portable_electric_wheelchair_toilet_move_wheel_nursi_754_78.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750097211/products/Kitchen_robot_automatic_electric_cooker_mixer_chopper_blende_Kitchen_robot_automatic_electric_cooker_mixer_chopper_blende_1168_7.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095734/products/Gym_Treadmill_Running_Machine_Foldable_Electric_Walking_Fitn_Gym_Treadmill_Running_Machine_Foldable_Electric_Walking_Fitn_306_9.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750090435/products/2021_new_kitchen_appliances_electric_drum_type_multifunction_2021_new_kitchen_appliances_electric_drum_type_multifunction_2013_7.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120067/products/Tiansta_380V_15000W_Single_Burner_Induction_Cooktop_Electric_Tiansta_380V_15000W_Single_Burner_Induction_Cooktop_Electric_628_57.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119998/products/TAP_New_Professional_Cardio_Gym_Equipment_Electric_Commercia_TAP_New_Professional_Cardio_Gym_Equipment_Electric_Commercia_845_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091495/products/4_burners_china_induction_cooker_commercial_electric_automat_4_burners_china_induction_cooker_commercial_electric_automat_437_8.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096592/products/Hot_Sale_Factory_Wholesale_Electric_Powered_Stair_Climbing_C_Hot_Sale_Factory_Wholesale_Electric_Powered_Stair_Climbing_C_845.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093462/products/Commercial_16KW_Customized_Vertical_4_Head_Cooker_Electric_C_Commercial_16KW_Customized_Vertical_4_Head_Cooker_Electric_C_2483.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096268/products/High_Quality_Leg_Lift_Full_Body_Electric_Adjustable_Homecare_High_Quality_Leg_Lift_Full_Body_Electric_Adjustable_Homecare_510.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091710/products/7L_mini_Colorful_Electric_Food_kitchen_home_appliances_stand_7L_mini_Colorful_Electric_Food_kitchen_home_appliances_stand_418.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092515/products/Bakery_Home_Cooking_Appliances_Horno_1_Single_Deck_Electric_Bakery_Home_Cooking_Appliances_Horno_1_Single_Deck_Electric_242.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094136/products/Dayoo_1800w_electric_home_appliances_for_cleaning_handheld_d_Dayoo_1800w_electric_home_appliances_for_cleaning_handheld_d_137_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092966/products/Built-in_Electric_Hob_6_burners_induction_cooktop_Built-in_E_Built-in_Electric_Hob_6_burners_induction_cooktop_825.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120478/products/Wholesale_Highway_4wd_40kmh_Speed_Quick_Charge_Electric_Long_Wholesale_Highway_4wd_40kmh_Speed_Quick_Charge_Electric_Long_247_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094522/products/European_warehouse_IE-B2_electric_bike_Outdoor_Sport_14Inch_European_warehouse_IE-B2_electric_bike_Outdoor_Sport_14Inch_598_13.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091282/products/240v_Wall_Mounted_stainless_steel_Cover_tankless_Electric_Sh_240v_Wall_Mounted_stainless_steel_Cover_tankless_Electric_Sh_317_9.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091807/products/80l_Built_In_Electric_Multifunction_Oven_digital_timer_contr_80l_Built_In_Electric_Multifunction_Oven_digital_timer_contr_291_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091253/products/20KW_Tankless_Instant_Electric_Water_Heater_for_Shower_Home_20KW_Tankless_Instant_Electric_Water_Heater_for_Shower_Home_312_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119171/products/Original_New_Stock_Electric_Power_Steering_Pump_For_Peugeot_Original_New_Stock_Electric_Power_Steering_Pump_For_Peugeot_192_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117847/products/Manufacturer_90cm_Multi_Function_Electric_Wall_Oven_Bakery_O_Manufacturer_90cm_Multi_Function_Electric_Wall_Oven_Bakery_O_310_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093483/products/Commercial_Pancake_Cake_Making_Non-Stick_Electric_Crepe_Make_Commercial_Pancake_Cake_Making_Non-Stick_Electric_Crepe_Make_289_3.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092961/products/Brewista_Electric_Gooseneck_coffee_Kettle_Pour_Over_Kettle_E_Brewista_Electric_Gooseneck_coffee_Kettle_Pour_Over_Kettle_E_301_6.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095179/products/Fitness_Home_Sports_Running_Machine_Electric_Health-Mate_Tou_Fitness_Home_Sports_Running_Machine_Electric_Health-Mate_Tou_949_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119510/products/Public_electric_freestanding_water_dispensers_with_hot_and_c_Public_electric_freestanding_water_dispensers_with_hot_and_c_2259_4.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094655/products/Factory_Price_Dough_Mixer_Home_Appliances_Electric_Hand_Mixe_Factory_Price_Dough_Mixer_Home_Appliances_Electric_Hand_Mixe_280_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091403/products/45L_non-stick_cooker_intelligent_electric_pressure_cooker_ex_45L_non-stick_cooker_intelligent_electric_pressure_cooker_ex_1112_15.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117334/products/Luxury_Electric_Genuine_LeatherHigh_Quality_Luxury_E_Home_Th_Luxury_Electric_Genuine_LeatherHigh_Quality_Luxury_E_Home_Th_1758_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094540/products/FEST_Electric_Beater_for_Cakes_5L_home_appliances_kitchen_Do_FEST_Electric_Beater_for_Cakes_5L_home_appliances_kitchen_Do_220.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119818/products/Smart_Home_1500mm_Single_Side_Openning_Electric_Log_Bio_Etha_Smart_Home_1500mm_Single_Side_Openning_Electric_Log_Bio_Etha_575.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750090325/products/2021_Boyueda_Beast_High_Speed_S3_5600W_Electric_Scooter_for_2021_Boyueda_Beast_High_Speed_S3_5600W_Electric_Scooter_for_1056.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093031/products/Car_parts_of_auto_steering_system_electric_power_steering_co_Car_parts_of_auto_steering_system_electric_power_steering_co_198.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091976/products/ADO_A20F_500W_folding_electric_bicycle_city_bike_exercise_mo_ADO_A20F_500W_folding_electric_bicycle_city_bike_exercise_mo_648.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119604/products/RUITAI_Professional_4_Range_gas_Stove_Machine_Electric_Gas_C_RUITAI_Professional_4_Range_gas_Stove_Machine_Electric_Gas_C_275.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094401/products/Easy_Cleaned_Stove_And_Oven_Outdoor_Electric_Cooktop_4_Burne_Easy_Cleaned_Stove_And_Oven_Outdoor_Electric_Cooktop_4_Burne_1342.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119816/products/Smad_65L_Built-in_Household_Electric_High_Quality_Pizza_Bake_Smad_65L_Built-in_Household_Electric_High_Quality_Pizza_Bake_293_7.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750089986/products/10L_Induction_fast_heat_safety_and_energy_saving_Electric_wa_10L_Induction_fast_heat_safety_and_energy_saving_Electric_wa_587_64.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096523/products/Horno_electrico_Home_major_kitchen_appliances_inbuilt_wall_c_Horno_electrico_Home_major_kitchen_appliances_inbuilt_wall_c_1105.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091831/products/8kw_single_Phase_wholesale_wall_hang_electric_boiler_for_hea_8kw_single_Phase_wholesale_wall_hang_electric_boiler_for_hea_409_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750097205/products/Kitchen_Electric_Cooktop_4_6_Burner_Gas_Stove_For_Cooking_Ki_Kitchen_Electric_Cooktop_4_6_Burner_Gas_Stove_For_Cooking_1586.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095768/products/HOBOT_298_Electric_Windows_Robot_Vacuum_Cleaner_Low_Price_Wi_HOBOT_298_Electric_Windows_Robot_Vacuum_Cleaner_Low_Price_Wi_769_98.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091251/products/20KW_Tankless_Instant_Electric_Water_Heater_380_Volt_50_Hz_C_20KW_Tankless_Instant_Electric_Water_Heater_380_Volt_50_Hz_C_275.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095244/products/Foshan_Electric_built_in_Oven_High_Quality_Built-In_wall_Ove_Foshan_Electric_built_in_Oven_High_Quality_Built-In_wall_Ove_110.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091698/products/7-speed_electric_mountain_bike_frame_500_750W_48V_fat_tire_7-speed_electric_mountain_bike_frame_500_750W_48V_fat_tire_1077_7.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096336/products/High_end_mid_drive_motor_ebike_sport_electric_bike_ready_to_High_end_mid_drive_motor_ebike_sport_electric_bike_ready_to_1143_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092077/products/All_In_One_Touch_Turkish_Electric_Turkish_Bean_To_Cup_Brand_All_In_One_Touch_Turkish_Electric_Turkish_Bean_To_Cup_Brand_383_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096529/products/Horus_HR-20_Best_Price_Top_Quality_Blender_Electric_Mixer_Fo_Horus_HR-20_Best_Price_Top_Quality_Blender_Electric_Mixer_Fo_299_27.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096590/products/Hot_Sale_Electrical_Appliances_Home_Office_Automatic_Espress_Hot_Sale_Electrical_Appliances_Home_Office_Automatic_Espress_748.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094561/products/FOTOVO_Electrical_appliances_carrying_rated_power_less_than_FOTOVO_Electrical_appliances_carrying_rated_power_less_than_3250.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094578/products/Factory_Cheap_Price_Quality_Electrical_Kitchen_Appliances_Sl_Factory_Cheap_Price_Quality_Electrical_Kitchen_Appliances_Sl_315_7.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093002/products/CES_medical_brain_stimulator_electrical_brain_stimulation_to_CES_medical_brain_stimulator_electrical_brain_stimulation_to_130_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117830/products/Magnificent_EcoRider_E7-2_2000W_Golf_Electric_Skateboard_Sco_We_are_a_leading_marketing_agency_that_utilIZES_over_10_year_Magnificent_EcoRider_E7-2_2000W_Golf_Electric_Skateboard_Sco.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119689/products/Restaurant_2_5Kw_4_Burner_Stove_Cooker_Kitchen_Electric_Cera_We_are_a_leading_marketing_agency_that_utilIZES_over_10_year_Restaurant_2_5Kw_4_Burner_Stove_Cooker_Kitchen_Electric_Cera.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119117/products/Offroad_electric_scooter_NANROBOT_D4_3_0_Dual_motor_Folding_We_are_a_leading_marketing_agency_that_utilIZES_over_10_year_Offroad_electric_scooter_NANROBOT_D4_3_0_Dual_motor_Folding.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096754/products/Household_Hot_Sales_Built-in_90cm_100L_Gas_Electrical_Oven_H_Household_Hot_Sales_Built-in_90cm_100L_Gas_Electrical_Oven_702_1.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118472/products/New_Arrival_Commercial_Rower_Machines_Use_Rowing_Machine_New_New_Arrival_Commercial_Rower_Machines_Use_Rowing_Machine_228_25.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092210/products/Automatic_Espresso_Machine_Coffee_Machine_Coffee_Maker_for_O_Automatic_Espresso_Machine_Coffee_Machine_Coffee_Maker_for_O_1419.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094414/products/Electric_Cooking_Home_Machine_And_Cooking_Pot_Making_Machine_Electric_Cooking_Home_Machine_And_Cooking_Pot_Making_Machine_527_99.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096507/products/Home_training_exercise_sport_machine_Home_training_exercise_Home_training_exercise_sport_machine_880.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091533/products/500L_Herb_Ultrasonic_Extraction_machine_500L_Herb_Ultrasonic_500L_Herb_Ultrasonic_Extraction_machine_16225.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118358/products/Multi-functional_exercise_squats_training_machine_Commercial_Multi-functional_exercise_squats_training_machine_Commercial_1313.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120143/products/Treadmill_fitness_equipment_treadmill_running_machine_sport_Treadmill_fitness_equipment_treadmill_running_machine_sport_782.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093506/products/Commercial_running_track_machine_curved_treadmill_Commercial_Commercial_running_track_machine_curved_treadmill_154_31.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118550/products/New_Designs_Commercial_Coffee_Machine_Electric_Appliance_New_New_Designs_Commercial_Coffee_Machine_Electric_Appliance_562_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750090228/products/2020_hot_selling_automatic_bread_proofing_machine_commercial_2020_hot_selling_automatic_bread_proofing_machine_commercial_1560.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095734/products/Gym_Treadmill_Running_Machine_Foldable_Electric_Walking_Fitn_Gym_Treadmill_Running_Machine_Foldable_Electric_Walking_Fitn_306_9.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093471/products/Commercial_Gym_equipment_Hoist_machine_Seated_Dip_Guarantee_Commercial_Gym_equipment_Hoist_machine_Seated_Dip_Guarantee_764_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096061/products/High-end_Fitness_Equipment_Rear_DeltPec_Fly_Machine_professi_High-end_Fitness_Equipment_Rear_DeltPec_Fly_Machine_professi_561.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119808/products/Single_disc_chassis_13_inch_polishing_cleaning_floor_machine_Single_disc_chassis_13_inch_polishing_cleaning_floor_machine_295.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091292/products/24_hour_automatically_medicine_condom_vending_machine_for_ph_24_hour_automatically_medicine_condom_vending_machine_for_ph_4800.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095989/products/Health_Care_Supplies_Foot_Detox_Machine_Hydrogen_Ion_Massage_Health_Care_Supplies_Foot_Detox_Machine_Hydrogen_Ion_Massage_1100.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094436/products/Electric_Stainless_Steel_Wheat_Flour_Milling_Machine_Wet_And_Electric_Stainless_Steel_Wheat_Flour_Milling_Machine_Wet_And_430_1.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117486/products/Luxury_table_home_appliance_shop_use_coffee_machine_espresso_Luxury_table_home_appliance_shop_use_coffee_machine_espresso_137_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120134/products/Transfer_Chair_Multi-function_Shift_Machine_Patient_Lift_Mac_Transfer_Chair_Multi-function_Shift_Machine_Patient_Lift_Mac_511_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096683/products/Hot_sale_Professional_Hotel_Office_Sports_Running_Machine_Co_Hot_sale_Professional_Hotel_Office_Sports_Running_Machine_Co_2200.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092630/products/Best_Gym_Smith_Machine_Strength_Training_Cable_Crossover_Tra_Best_Gym_Smith_Machine_Strength_Training_Cable_Crossover_Tra_1313.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096845/products/Indoor_body_building_home_gym_equipment_fitness_machine_exer_Indoor_body_building_home_gym_equipment_fitness_machine_exer_86_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094436/products/Electric_Stainless_Steel_Wheat_Flour_Milling_Machine_Wet_And_Electric_Stainless_Steel_Wheat_Flour_Milling_Machine_Wet_And_430_1.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117486/products/Luxury_table_home_appliance_shop_use_coffee_machine_espresso_Luxury_table_home_appliance_shop_use_coffee_machine_espresso_137_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095179/products/Fitness_Home_Sports_Running_Machine_Electric_Health-Mate_Tou_Fitness_Home_Sports_Running_Machine_Electric_Health-Mate_Tou_949_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120134/products/Transfer_Chair_Multi-function_Shift_Machine_Patient_Lift_Mac_Transfer_Chair_Multi-function_Shift_Machine_Patient_Lift_Mac_511_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092794/products/Best_herbal_medicine_cutter_herbs_cutting_machine_herb_slici_Best_herbal_medicine_cutter_herbs_cutting_machine_herb_slici_533_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119604/products/RUITAI_Professional_4_Range_gas_Stove_Machine_Electric_Gas_C_RUITAI_Professional_4_Range_gas_Stove_Machine_Electric_Gas_C_275.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094489/products/Espresso_Machine_Home_Smart_Appliance_Steam_Milk_Foam_All-in_Espresso_Machine_Home_Smart_Appliance_Steam_Milk_Foam_All-in_219_99.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091660/products/6KG_FULLY_Automatic_TOP_LOADING_Washing_Machine_for_Home_Ele_6KG_FULLY_Automatic_TOP_LOADING_Washing_Machine_for_Home_Ele_97_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096055/products/High-Precision_Scientific_Research_Machine_Vision_Industrial_We_are_a_leading_marketing_agency_that_utilIZES_over_10_year_High-Precision_Scientific_Research_Machine_Vision_Industrial.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095171/products/Fitness_Equipment_3_People_Station_Gym_Equipment_Multi-Funct_Fitness_Equipment_3_People_Station_Gym_Equipment_Multi-Funct_462.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094169/products/Dental_equipments_unit_gnatus_types_of_dental_chair_instrume_Dental_equipments_unit_gnatus_types_of_dental_chair_instrume_1045.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119944/products/Strength_gym_fitness_equipment_multi_gym_rack_sport_equipmen_Strength_gym_fitness_equipment_multi_gym_rack_sport_equipmen_858.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118180/products/Modern_design_KY123_Automatic_Rehabilitation_treatment_equip_Modern_design_KY123_Automatic_Rehabilitation_treatment_equip_429_6.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119366/products/Photographic_equipment_Photo_Studio_Continuous_Lighting_Kit_Photographic_equipment_Photo_Studio_Continuous_Lighting_Kit_550.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094169/products/Dental_equipments_unit_gnatus_types_of_dental_chair_instrume_Dental_equipments_unit_gnatus_types_of_dental_chair_instrume_1045.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095184/products/Fitness_Sports_equipment_indoor_spinning_bike_bicycle_Uprigh_Fitness_Sports_equipment_indoor_spinning_bike_bicycle_Uprigh_407.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094011/products/Customized_amusement_park_equipment_luminous_kids_riding_bik_Customized_amusement_park_equipment_luminous_kids_riding_bik_2600.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117920/products/Medical_equipment_Cheap_Multi-purpose_Stainless_Steel_Orthop_Medical_equipment_Cheap_Multi-purpose_Stainless_Steel_Orthop_858.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094717/products/Factory_Supply_Dumbbell_Commercial_Gym_Equipment_Silver_Spor_Factory_Supply_Dumbbell_Commercial_Gym_Equipment_Silver_Spor_90_2.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094695/products/Factory_Source_Commercial_Home_Gym_Equipment_Sport_Enterta_Factory_Source_Commercial_Home_Gym_Equipment_Sport_Enterta_650.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092472/products/BYOND_health_care_ambulances_equipment_price_medical_ventila_BYOND_health_care_ambulances_equipment_price_medical_ventila_253.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119998/products/TAP_New_Professional_Cardio_Gym_Equipment_Electric_Commercia_TAP_New_Professional_Cardio_Gym_Equipment_Electric_Commercia_845_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095166/products/Fitness_Adjustable_Weightlifting_Bed_Gym_Equipment_Barbell_D_Fitness_Adjustable_Weightlifting_Bed_Gym_Equipment_Barbell_D_43_69.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093651/products/Custom_Fitness_Equipment_Gymnastics_Water_Sports_Floating_In_Custom_Fitness_Equipment_Gymnastics_Water_Sports_Floating_In_116_82.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119395/products/Portable_Excellent_Medical_Equipment_China_Digital_Hearing_A_Portable_Excellent_Medical_Equipment_China_Digital_Hearing_A_188_8.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096061/products/High-end_Fitness_Equipment_Rear_DeltPec_Fly_Machine_professi_High-end_Fitness_Equipment_Rear_DeltPec_Fly_Machine_professi_561.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092038/products/ASITA_Wall_Mounted_Portable_Fitness_Equipment_Tonal_Digital_ASITA_Wall_Mounted_Portable_Fitness_Equipment_Tonal_Digital_1978_9.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120054/products/The_latest_gym_sports_indoor_fitness_equipment_multifunction_The_latest_gym_sports_indoor_fitness_equipment_multifunction_97_13.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093480/products/Commercial_Home_Gyms_Equipment_maquinas_de_sports_fitness_ac_Commercial_Home_Gyms_Equipment_maquinas_de_sports_fitness_ac_461_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093467/products/Commercial_Gym_Strength_Equipment_4-Way_Neck_Sports_Exercise_Commercial_Gym_Strength_Equipment_4-Way_Neck_Sports_Exercise_638.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094164/products/Dental_Equipment_Wall-mounted_Led_Surgical_Exam_Light_Dental_Dental_Equipment_Wall-mounted_Led_Surgical_Exam_Light_Dental_455.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119470/products/Professional_Commercial_Kitchen_Equipment_Industrial_Electri_We_are_a_leading_marketing_agency_that_utilIZES_over_10_year_Professional_Commercial_Kitchen_Equipment_Industrial_Electri.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119781/products/SRH-73_Dezhou_fitness_strength_equipment_sport_fit_free_weig_SRH-73_Dezhou_fitness_strength_equipment_sport_fit_free_weig_567_03.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096840/products/Indoor_Foldable_Heavy_Duty_Commercial_Sport_Gym_Equipment_Cy_Indoor_Foldable_Heavy_Duty_Commercial_Sport_Gym_Equipment_Cy_245_3.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120271/products/Weight_Plate_Loaded_Iso-Lateral_Wide_Pulldown_Gym_Equipment_Weight_Plate_Loaded_Iso-Lateral_Wide_Pulldown_Gym_Equipment_445_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117900/products/Medical_Artificial_Limbs_Legs_Gel_Liner_With_Lock_Prosthetic_Medical_Artificial_Limbs_Legs_Gel_Liner_With_Lock_Prosthetic_336.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121231/products/medical_portable_electric_wheelchair_toilet_move_wheel_nursi_medical_portable_electric_wheelchair_toilet_move_wheel_nursi_754_78.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117895/products/Medical_Anesthesia_TrolleyEmergency_TrolleyMedicine_Cart_Med_Medical_Anesthesia_TrolleyEmergency_TrolleyMedicine_Cart_576.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117930/products/Medical_health_device_adjustable_foldable_electric_power_wid_Medical_health_device_adjustable_foldable_electric_power_wid_3300.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117937/products/Medicine_In_Emergency_Trolley_And_Drugs_Trolley_Suppliers_Me_Medicine_In_Emergency_Trolley_And_Drugs_Trolley_Suppliers_480.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121234/products/medical_supplies_high_concentration_oxygen_concentrator_medi_medical_supplies_high_concentration_oxygen_concentrator_1430.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117916/products/Medical_Ultrasound_Instruments_Mindray_Portable_Color_Dopple_Medical_Ultrasound_Instruments_Mindray_Portable_Color_Dopple_11698_7.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096789/products/IT-530_Iontech_best_countertop_alkaline_water_cooler_for_hom_IT-530_Iontech_best_countertop_alkaline_water_cooler_for_hom_605.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096789/products/IT-530_Iontech_best_countertop_alkaline_water_cooler_for_hom_IT-530_Iontech_best_countertop_alkaline_water_cooler_for_hom_605.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118100/products/Mini_Air_Conditioner_Cooler_Portable_5000Btu_Led_Light_House_Mini_Air_Conditioner_Cooler_Portable_5000Btu_Led_Light_House_140_8.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091427/products/46L_china_home_appliances_micro_cool_mini_refrigerator_with_46L_china_home_appliances_micro_cool_mini_refrigerator_with_103_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121592/products/wholesale_high_quality_4995266_auto_ISF2_8_engine_cylinder_p_We_are_a_leading_marketing_agency_that_utilIZES_over_10_year_wholesale_high_quality_4995266_auto_ISF2_8_engine_cylinder_p.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092150/products/Auto_Engine_Parts_2AZ_FE_balance_shaft_for_Toyota_Camry_High_Auto_Engine_Parts_2AZ_FE_balance_shaft_for_Toyota_Camry_High_218_93.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092302/products/BBmart_Auto_Spare_Car_Parts_High_Quality_4H0199255AA_Engine_BBmart_Auto_Spare_Car_Parts_High_Quality_4H0199255AA_Engine_993_17.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118348/products/Motor_spare_parts_M11_diesel_engine_forged_steel_crankshaft_Motor_spare_parts_M11_diesel_engine_forged_steel_crankshaft_650.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094115/products/Dakang_2MP_LPRANPR_Automatic_Vehicle_License_Plate_System_Cc_Dakang_2MP_LPRANPR_Automatic_Vehicle_License_Plate_System_Cc_715.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117550/products/MDRF375_Home_Appliances_Double_Door_Bottom_Freezer_Refrigera_MDRF375_Home_Appliances_Double_Door_Bottom_Freezer_Refrigera_276.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750090422/products/2021_P_M_New_Design_Mini_portable_medicine_refrigerator_for_2021_P_M_New_Design_Mini_portable_medicine_refrigerator_for_200_6.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091427/products/46L_china_home_appliances_micro_cool_mini_refrigerator_with_46L_china_home_appliances_micro_cool_mini_refrigerator_with_103_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091588/products/60L_New_best_sell_Home_appliances_mini_refrigerator_60L_New_60L_New_best_sell_Home_appliances_mini_refrigerator_132.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117546/products/MDRF375_300L_Manufacturers_Home_Appliance_Eletronic_Refriger_MDRF375_300L_Manufacturers_Home_Appliance_Eletronic_Refriger_253.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094274/products/Diagnostic_medical_device_CONTEC_ECG1200G_ecg_monitor_12_lea_Diagnostic_medical_device_CONTEC_ECG1200G_ecg_monitor_12_lea_720.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119680/products/Rehabilitation_Treatment_Device_Prevent_muscle_atrophy_Rehab_Rehabilitation_Treatment_Device_Prevent_muscle_atrophy_189_04.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118072/products/Metal_floor_free_standing_multi-functional_sports_storage_ho_Metal_floor_free_standing_multi-functional_sports_storage_ho_43_97.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119188/products/Original_Pre-owned_brand_FE24-704_ZA_OSS_T_image-proof_micro_Original_Pre-owned_brand_FE24-704_ZA_OSS_T_image-proof_micro_590_7.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118080/products/Micro_Power_Consumption_2MP_1080P_48W_4PCS_Solar_Panel_Sim_C_Micro_Power_Consumption_2MP_1080P_48W_4PCS_Solar_Panel_Sim_C_196_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094404/products/Eco-friendly_transparent_optical_eyeglass_glasses_Part_Spect_Eco-friendly_transparent_optical_eyeglass_glasses_Part_Spect_2080.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095541/products/Glistuning_Smoked_Tail_Lights_For_5_Series_China_Car_Part_Au_Glistuning_Smoked_Tail_Lights_For_5_Series_China_Car_Part_Au_325.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117541/products/MCOSS_Men_s_Off-Road_Motorcycle_Boots_for_Men_Dirt_Bike_Moto_MCOSS_Men_s_Off-Road_Motorcycle_Boots_for_Men_Dirt_Bike_Moto_253_99.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750091698/products/7-speed_electric_mountain_bike_frame_500_750W_48V_fat_tire_7-speed_electric_mountain_bike_frame_500_750W_48V_fat_tire_1077_7.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750097146/products/JOYKIE_wholesale_21_speed_bicicletas_bicycle_mountain_bike_2_JOYKIE_wholesale_21_speed_bicicletas_bicycle_mountain_bike_2_111_55.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096051/products/Herolion_Fat_Tire_350W_Motor_Bicicleta_Electric_E_Bikes_Bicy_Herolion_Fat_Tire_350W_Motor_Bicicleta_Electric_E_Bikes_Bicy_657_8.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119882/products/Spinning_Bike_Indoor_Spining_Exercise_Spinning_Bike_Body_Fit_Spinning_Bike_Indoor_Spining_Exercise_Spinning_Bike_Body_Fit_330.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096051/products/Herolion_Fat_Tire_350W_Motor_Bicicleta_Electric_E_Bikes_Bicy_Herolion_Fat_Tire_350W_Motor_Bicicleta_Electric_E_Bikes_Bicy_657_8.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119416/products/Power_wheelchair_lightweight_detachable_motorized_mobility_w_Power_wheelchair_lightweight_detachable_motorized_mobility_w_1331.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117933/products/Medical_motorised_wheelchair_with_electric_and_manual_model_Medical_motorised_wheelchair_with_electric_and_manual_model_660.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120152/products/Two_Piece_Full_Motorbike_Clothing_Motorcycle_Racing_Suit_Lea_Two_Piece_Full_Motorbike_Clothing_Motorcycle_Racing_Suit_Lea_385.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750118348/products/Motor_spare_parts_M11_diesel_engine_forged_steel_crankshaft_Motor_spare_parts_M11_diesel_engine_forged_steel_crankshaft_650.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750090779/products/2022_New_Trending_Four_Motor_Remote_Control_Medical_Bed_Pati_2022_New_Trending_Four_Motor_Remote_Control_Medical_Bed_Pati_540.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120374/products/Wholesale_FRP_Car_Parts_Auto_Front_Bumper_CSS_Style_Wide_Bod_Wholesale_FRP_Car_Parts_Auto_Front_Bumper_CSS_Style_Wide_Bod_1100.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119766/products/SM-MR30_380V_Mid_Rise_Scissor_Car_Lift_SM-MR30_380V_Mid_Rise_SM-MR30_380V_Mid_Rise_Scissor_Car_Lift_1249_6.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120155/products/Two_way_push_baby_pram_stroller_rotation_360_degree_baby_car_Two_way_push_baby_pram_stroller_rotation_360_degree_baby_car_185.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119016/products/OEM_Off_road_4x4_auto_parts_for_FJ767879_Front_Bumper_car_bu_OEM_Off_road_4x4_auto_parts_for_FJ767879_Front_Bumper_car_bu_379_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092559/products/Bebebus_safe_in_car_2_in_1_baby_stroller_stroller_pram_baby_Bebebus_safe_in_car_2_in_1_baby_stroller_stroller_pram_baby_298_8.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750090217/products/2019--New_Type_4000kg_hydraulic_2_post_car_lift_fo_2019--New_2019--New_Type_4000kg_hydraulic_2_post_car_lift_fo_977_9.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095981/products/Headlight_auto_car_parts_for_audi_a6_c7_headlight_2016-2018_Headlight_auto_car_parts_for_audi_a6_c7_headlight_2016-2018_632_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121648/products/wood_doll_child_3_wheels_joggerwholesale_doll_parasol_car_se_wood_doll_child_3_wheels_joggerwholesale_doll_parasol_car_se_91_08.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095741/products/HD_IR_car_thermal_infrared_wireless_mini_camera_module_HD_IR_HD_IR_car_thermal_infrared_wireless_mini_camera_module_2200.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119265/products/Outdoor_portable_power_station_2000W_for_EV_auto_car_Electri_Outdoor_portable_power_station_2000W_for_EV_auto_car_Electri_968.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094428/products/Electric_Mini_Smart_Car_Electric_Four-wheeler_New_Energy_Hom_Electric_Mini_Smart_Car_Electric_Four-wheeler_New_Energy_Hom_3069.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096090/products/High_Quality_Car_Upgrade_Kit_For_Spinthiace_Style_Body_Parts_High_Quality_Car_Upgrade_Kit_For_Spinthiace_Style_Body_Parts_1300.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121424/products/smart_home_display_cabinets_smart_home_showcase_easy_to_car_smart_home_display_cabinets_smart_home_showcase_easy_to_car_1261.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095526/products/Genuine_car_parts_BodyKits_For_2013-2018_Volkswagen_CC_upgra_Genuine_car_parts_BodyKits_For_2013-2018_Volkswagen_CC_upgra_528.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096255/products/High_Quality_JDM_Steel_Lambo_Doors_Car_Open_Part_Accessories_High_Quality_JDM_Steel_Lambo_Doors_Car_Open_Part_Accessories_165.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121552/products/wholesale_CE_500KG_Hoist_Stand_car_lift_Jack_Stand_wholesale_wholesale_CE_500KG_Hoist_Stand_car_lift_Jack_Stand_85_8.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750090331/products/2021_High_Quality_Car_Accessories_Black_Lighting_System_Auto_2021_High_Quality_Car_Accessories_Black_Lighting_System_Auto_340_99.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092302/products/BBmart_Auto_Spare_Car_Parts_High_Quality_4H0199255AA_Engine_BBmart_Auto_Spare_Car_Parts_High_Quality_4H0199255AA_Engine_993_17.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094395/products/ESWING_2022_two_wheels_balance_car_Self_Balancing_ESWING_202_ESWING_2022_two_wheels_balance_car_Self_Balancing_1097_8.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119750/products/SFI_Approved_Car_Racing_BootsInternational_Auto_Race_Shoes_S_SFI_Approved_Car_Racing_BootsInternational_Auto_Race_Shoes_163_61.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095214/products/For_Club_Car_OEM_102595021_103974821_Golf_Cart_Accelerator_For_Club_Car_OEM_102595021_103974821_Golf_Cart_Accelerator_143.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121664/products/yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_yujiang_C_yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_40_15.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092126/products/Auto_Electric_Car_Spare_Parts_Japanese_Korean_Car_For_Hiace_Auto_Electric_Car_Spare_Parts_Japanese_Korean_Car_For_Hiace_361_24.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093026/products/Car_body_kits_Other_auto_accessories_facelift_update_kits_mo_Car_body_kits_Other_auto_accessories_facelift_update_kits_mo_276_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093031/products/Car_parts_of_auto_steering_system_electric_power_steering_co_Car_parts_of_auto_steering_system_electric_power_steering_co_198.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092284/products/B17_China_has_kitchen_cooktop_stoves_gas_cooker_combination_B17_China_has_kitchen_cooktop_stoves_gas_cooker_combination_660.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093139/products/Ceramic_Flower_Bouquet_3_Heads_Small_Wrought_Iron_Pendant_La_Ceramic_Flower_Bouquet_3_Heads_Small_Wrought_Iron_Pendant_La_152_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750300677/products/Diesel_Mr_Daddy_2_0_Men_s_Watch_with_Oversized_Chronograph_Bold_ironic_and_never_shy_Diesel_doesn_t_follow_trends_it_Diesel_Mr_Daddy_2_0_Men_s_Watch_with_Oversized_Chronograph.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120689/products/Wholesales_New_style_modern_light_luxury_table_lamp_living_r_Wholesales_New_style_modern_light_luxury_table_lamp_living_r_121.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750093376/products/Chuse_Modern_Minimalist_Nordic_Led_Floor_Light_Marble_Flor_L_Chuse_Modern_Minimalist_Nordic_Led_Floor_Light_Marble_Flor_L_62_7.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750090442/products/2021_popular_leds_lights_cobra_head_light_led_street_lamp_fo_2021_popular_leds_lights_cobra_head_light_led_street_lamp_fo_69_61.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119366/products/Photographic_equipment_Photo_Studio_Continuous_Lighting_Kit_Photographic_equipment_Photo_Studio_Continuous_Lighting_Kit_550.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119962/products/Stroller_Baby_3_in_1_Light_fold_Two-way_High-view_Baby_Pr_Stroller_Baby_3_in_1_Light_fold_Two-way_High-view_Baby_Pr_79_18.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119762/products/SIBOASI_Training_Speed_Reaction_Light_for_Improved_Speed_Rea_SIBOASI_Training_Speed_Reaction_Light_for_Improved_Speed_Rea_264.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119896/products/Sports_Training_Partner_Agile_Reaction_Light_for_Football_Ba_Sports_Training_Partner_Agile_Reaction_Light_for_Football_Ba_266_2.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750117226/products/Lightweight_Aluminum_Alloy_Manual_Electric_Power_Wheelchair_Lightweight_Aluminum_Alloy_Manual_Electric_Power_Wheelchair_696.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750095811/products/Hair_salon_mirror_Led_light_mirror_with_gold_frame_lighted_v_Hair_salon_mirror_Led_light_mirror_with_gold_frame_lighted_v_137_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120061/products/ThinkRider_X7_pro_direct_drive_smart_Bicycle_trainer_for_Ind_ThinkRider_X7_pro_direct_drive_smart_Bicycle_trainer_for_Ind_502_8.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092038/products/ASITA_Wall_Mounted_Portable_Fitness_Equipment_Tonal_Digital_ASITA_Wall_Mounted_Portable_Fitness_Equipment_Tonal_Digital_1978_9.png",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120244/products/Wall_Mount_43_WIFI_RJ45_Quad_Core_4G_LTE_Tablet_43_inch_RAM_Wall_Mount_43_WIFI_RJ45_Quad_Core_4G_LTE_Tablet_43_inch_RAM_708_4.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096331/products/High_brightness_Portable_Projector_Home_theater_Video_DLP_An_High_brightness_Portable_Projector_Home_theater_Video_DLP_An_438_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750119830/products/Smart_Projection_Screen_Handwriting_Touch_Conference_Live_Lc_Smart_Projection_Screen_Handwriting_Touch_Conference_Live_Lc_3346_79.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096836/products/Indoor_Decoration_Light_Wood_Fish_Project_Large_Hotel_Lobby_Indoor_Decoration_Light_Wood_Fish_Project_Large_Hotel_Lobby_55.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096898/products/Interactive_Workout_Smart_Home_Full_Size_Body_Smart_Fitness_Interactive_Workout_Smart_Home_Full_Size_Body_Smart_Fitness_528_44.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750120131/products/Traditional_Luxury_Antique_7_Balls_Mosaic_Glass_Turkish_Hang_Traditional_Luxury_Antique_7_Balls_Mosaic_Glass_Turkish_Hang_108_9.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750094305/products/Drop_ShippingCardot_China_Automobile_Accessories_Moto_Online_Drop_ShippingCardot_China_Automobile_Accessories_Moto_Online_203_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750092173/products/Auto_Parts_Accessories_Snorkel_LowHigh_Mount_for_Jeep_Wrangl_Auto_Parts_Accessories_Snorkel_LowHigh_Mount_for_Jeep_Wrangl_227_5.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750096541/products/Hot_Mom_360_Rotation_Baby_Stroller_Wheelchair_Accessories_3_Hot_Mom_360_Rotation_Baby_Stroller_Wheelchair_Accessories_3_536_25.jpg",
  "https://res.cloudinary.com/dhubpqnss/image/upload/v1750121226/products/maiker_offroad_4x4_auto_body_systems_accessories_parts_for_s_maiker_offroad_4x4_auto_body_systems_accessories_parts_for_s_312.jpg"
];

/* Build product objects with name and a short description (furniture-focused) */
const products = productUrls.map((url, idx) => {
  const name = friendlyNameFromUrl(url);
  const lower = name.toLowerCase();
  const desc = (() => {
    if (lower.includes("sofa") || lower.includes("couch") || lower.includes("sectional") || lower.includes("divan")) {
      return "Comfortable sofas & sectionals — premium upholstery and lasting comfort.";
    }
    if (lower.includes("bed") || lower.includes("mattress") || lower.includes("loft") || lower.includes("bunk")) {
      return "Beds & bedroom furniture — solid construction and elegant designs.";
    }
    if (lower.includes("table") || lower.includes("coffee") || lower.includes("dining") || lower.includes("desk")) {
      return "Tables & desks — functional, stylish surfaces for every room.";
    }
    if (lower.includes("chair") || lower.includes("armrest") || lower.includes("stool") || lower.includes("high chair") || lower.includes("high_chair") ) {
      return "Chairs & seating — ergonomics and style combined.";
    }
    if (lower.includes("lamp") || lower.includes("lighting") || lower.includes("bedside") || lower.includes("mirror")) {
      return "Lighting & decor — accent pieces to brighten your home.";
    }
    if (lower.includes("wardrobe") || lower.includes("dresser") || lower.includes("cabinet") || lower.includes("storage")) {
      return "Storage & wardrobes — keep your space organized with style.";
    }
    if (lower.includes("outdoor") || lower.includes("patio") || lower.includes("garden") || lower.includes("party")) {
      return "Outdoor & patio furniture — durable and weather-resistant.";
    }
    if (lower.includes("hospital") || lower.includes("medical") || lower.includes("surgical") || lower.includes("wheelchair") || lower.includes("patient")) {
      return "Professional-grade medical furniture & equipment.";
    }
    return "Quality furniture and home decor — crafted for comfort and style.";
  })();

  return {
    id: idx + 1,
    name,
    desc,
    img: url
  };
});

export default function Commodity() {
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 8; // exactly 8 products per page (4 up-down left, 4 up-down right)
  const total = products.length;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));

  const pageProducts = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    return products.slice(start, start + pageSize);
  }, [currentPage]);

  // split into two vertical columns: left (items 0-3) and right (items 4-7)
  const leftColumn = pageProducts.slice(0, 4);
  const rightColumn = pageProducts.slice(4, 8);

  const goTo = (page) => {
    const p = Math.max(1, Math.min(totalPages, page));
    setCurrentPage(p);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const pageNumbers = useMemo(() => {
    const maxButtons = 7;
    if (totalPages <= maxButtons) return Array.from({ length: totalPages }, (_, i) => i + 1);
    const half = Math.floor(maxButtons / 2);
    let start = Math.max(1, currentPage - half);
    let end = start + maxButtons - 1;
    if (end > totalPages) {
      end = totalPages;
      start = end - maxButtons + 1;
    }
    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  }, [currentPage, totalPages]);

  return (
    <div className="shoes-bg">
      <style>{`
        /* Navy strip behind the product grid */
        .shoes-grid-outer {
          background: #08223a;
          padding: 18px 10px;
        }

        /* Two columns layout: left and right columns stacked vertically */
        .two-column-vertical {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 18px;
          max-width: 1200px;
          margin: 0 auto;
        }

        /* Column container holds 4 stacked cards */
        .column-stack {
          display: flex;
          flex-direction: column;
          gap: 18px;
        }

        /* Frame around each card to match screenshot look */
        .shoe-card-frame {
          border: 8px solid #071e2f;
          box-sizing: border-box;
          background: #ffffff;
          display: flex;
          flex-direction: column;
          overflow: hidden;
          text-decoration: none;
          min-height: 280px;
        }

        /* Image wrapper keeps consistent aspect and scales */
        .shoe-image-wrap {
          width: 100%;
          padding-top: 56%;
          position: relative;
          overflow: hidden;
          background: #fff;
          flex: 0 0 auto;
        }
        .shoe-image-wrap img {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          object-fit: cover;
          display: block;
        }

        .shoe-info {
          padding: 14px;
          background: #fff;
          flex: 1 1 auto;
        }

        .shoe-name {
          font-size: 18px;
          font-weight: 700;
          color: #0b2b4a;
          margin: 0;
          line-height: 1.15;
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
          overflow: hidden;
        }
        .shoe-desc {
          margin-top: 8px;
          margin-bottom: 0;
          color: #6b6f76;
          font-size: 13px;
          line-height: 1.35;
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
          overflow: hidden;
        }

        /* Pagination style */
        .pagination-wrap {
          display:flex;
          justify-content:center;
          padding: 22px 0 44px;
        }
        .pagination-wrap button {
          margin: 0 6px;
          padding: 8px 12px;
          border-radius: 4px;
          border: 1px solid #d6d6d6;
          background: #fff;
          cursor: pointer;
          font-weight: 700;
          color: #111;
        }
        .pagination-wrap button.active {
          background: #1e90ff;
          color: #fff;
          border-color: #1e90ff;
        }

        /* Small screens: collapse to single column (keeps readable) */
        @media (max-width: 900px) {
          .two-column-vertical {
            grid-template-columns: 1fr;
            padding: 0 12px;
          }
        }

        /* Extra small screens: reduce frame thickness and font sizes */
        @media (max-width: 520px) {
          .shoe-card-frame { border-width: 4px; min-height: 220px; }
          .shoe-name { font-size: 15px; }
          .shoe-desc { font-size: 12px; }
        }
      `}</style>

      <main className="shoes-main">
        {/* Hero Section: background uses the imported Commodities.png asset */}
        <section
          className="shoes-hero"
          style={{
            backgroundImage: `url(${ShoesHero})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
            minHeight: "320px"
          }}
        >
          <div className="shoes-hero-content" style={{ paddingTop: 80, paddingBottom: 80 }}>
            <h2 className="shoes-category">Commodities</h2>
            <h1 className="shoes-title">Explore Our Collection For Commodities</h1>
            <p className="shoes-subtitle">
              Updated weekly with new arrivals and curated selections for your home.
            </p>
          </div>
        </section>

        {/* Products found row */}
        <div style={{ maxWidth: "1200px", margin: "10px auto 6px", padding: "0 12px", color: "#071e3d", fontWeight: 700 }}>
          {total} products found.
        </div>

        {/* Navy background strip with two vertical columns */}
        <div className="shoes-grid-outer" aria-hidden="false">
          <div className="two-column-vertical">
            {/* Left column: top-to-bottom (4 items) */}
            <div className="column-stack" role="list">
              {leftColumn.map((p) => (
                <a
                  key={p.id}
                  href={`/furniture/${p.id}`}
                  className="shoe-card-frame"
                  role="listitem"
                  title={`${p.name} — ${p.desc}`}
                >
                  <div className="shoe-image-wrap">
                    <img src={p.img} alt={p.name} />
                  </div>
                  <div className="shoe-info">
                    <h3 className="shoe-name">{p.name}</h3>
                    <p className="shoe-desc">{p.desc}</p>
                  </div>
                </a>
              ))}
            </div>

            {/* Right column: top-to-bottom (4 items) */}
            <div className="column-stack" role="list">
              {rightColumn.map((p) => (
                <a
                  key={p.id}
                  href={`/furniture/${p.id}`}
                  className="shoe-card-frame"
                  role="listitem"
                  title={`${p.name} — ${p.desc}`}
                >
                  <div className="shoe-image-wrap">
                    <img src={p.img} alt={p.name} />
                  </div>
                  <div className="shoe-info">
                    <h3 className="shoe-name">{p.name}</h3>
                    <p className="shoe-desc">{p.desc}</p>
                  </div>
                </a>
              ))}
            </div>
          </div>
        </div>

        {/* Pagination */}
        <div className="pagination-wrap" aria-label="Pagination">
          <button onClick={() => goTo(currentPage - 1)} disabled={currentPage === 1} aria-label="Previous page">
            {"<"}
          </button>

          {pageNumbers[0] > 1 && (
            <>
              <button onClick={() => goTo(1)}>1</button>
              {pageNumbers[0] > 2 && <span style={{ alignSelf: "center", margin: "0 6px", color: "#fff" }}>…</span>}
            </>
          )}

          {pageNumbers.map((n) => (
            <button
              key={n}
              onClick={() => goTo(n)}
              className={n === currentPage ? "active" : ""}
              aria-current={n === currentPage ? "page" : undefined}
            >
              {n}
            </button>
          ))}

          {pageNumbers[pageNumbers.length - 1] < totalPages && (
            <>
              {pageNumbers[pageNumbers.length - 1] < totalPages - 1 && <span style={{ alignSelf: "center", margin: "0 6px", color: "#fff" }}>…</span>}
              <button onClick={() => goTo(totalPages)}>{totalPages}</button>
            </>
          )}

          <button onClick={() => goTo(currentPage + 1)} disabled={currentPage === totalPages} aria-label="Next page">
            {">"}
          </button>
        </div>
      </main>
    </div>
  );
}