import React, { useMemo, useState } from "react";
import "./Shoes.css";
// IMPORT the hero image from your src tree so the bundler resolves it correctly.
// Adjust the path if your image is in a different folder under src.
import ShoesHero from "../assets/images/dashboard/accessories2.png";

/* Helper: build a friendly name from the Cloudinary filename */
function friendlyNameFromUrl(url) {
  try {
    const parts = url.split("/");
    let name = parts[parts.length - 1] || url;
    name = name.replace(/\.[a-zA-Z0-9]+$/, "");
    name = name.replace(/(_\d+){1,3}$/, "");
    name = name.replace(/[_]+/g, " ").replace(/\s{2,}/g, " ").trim();
    if (name.length > 60) return name.slice(0, 57) + "...";
    return decodeURIComponent(name);
  } catch {
    return url;
  }
}

/* All Cloudinary product URLs provided by the user (replaced as requested) */
const productUrls = [
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635801/products/travel_luggage_bag_for_men_large_keepall_camping_bags_sport_travel_luggage_bag_for_men_large_keepall_camping_bags_sport_257_4.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635801/products/travel_luggage_bag_for_men_large_keepall_camping_bags_sport_travel_luggage_bag_for_men_large_keepall_camping_bags_sport_257_4.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635816/products/yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_yujiang_C_yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_40_15.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635816/products/yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_yujiang_C_yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_40_15.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635816/products/yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_yujiang_C_yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_40_15.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635775/products/simple_2022_sunglasses_simple_2022_sunglasses_simple_2022_sunglasses_110.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635426/products/Ultra_Light_Women_Designer_Square_Sunglass_Frames_Men_Vintag_Ultra_Light_Women_Designer_Square_Sunglass_Frames_Men_Vintag_208_79.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635413/products/Top_Selling_Products_Floor_Cleaning_Robot_Low_Noise_Home_App_Top_Selling_Products_Floor_Cleaning_Robot_Low_Noise_Home_App_105_59.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635412/products/Top_Quality_Italian_Genuine_Leather_Promise_Mini_Lady_s_Hand_Top_Quality_Italian_Genuine_Leather_Promise_Mini_Lady_s_Hand_150_8.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635401/products/Togo_Leather_Handmade_honey_wax_platinum_bag_imported_calf_l_Togo_Leather_Handmade_honey_wax_platinum_bag_imported_calf_l_558_75.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635385/products/The_black_Cosmetic_bag_for_women_Cowhide_inner_material_Nile_The_black_Cosmetic_bag_for_women_Cowhide_inner_material_Nile_866_14.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635384/products/Textured_shape_high_quality_acetate_titanium_eye_frames_opti_Textured_shape_high_quality_acetate_titanium_eye_frames_opti_479_6.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635366/products/Swarovski_Millenia_Jewelry_Collection_Green_Octagon_Cut_Cry_Swarovski_Millenia_Jewelry_Collection_Green_Octagon_Cut_Cry_18064.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635358/products/Super_September_Shiny_Chainmail_Fabric_Metal_Sequin_Dress_Su_Super_September_Shiny_Chainmail_Fabric_Metal_Sequin_Dress_230.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635314/products/Smart_Household_Appliances_Modern_Black_Durable_Glass_Built-_Smart_Household_Appliances_Modern_Black_Durable_Glass_Built-_1320.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635308/products/Set_Of_3_Round_Shape_Black_Color_Mother_Of_Pearl_Riser_Servi_Set_Of_3_Round_Shape_Black_Color_Mother_Of_Pearl_Riser_Servi_132.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635292/products/SM-MR30_380V_Mid_Rise_Scissor_Car_Lift_SM-MR30_380V_Mid_Rise_SM-MR30_380V_Mid_Rise_Scissor_Car_Lift_1249_6.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635276/products/Russian_Style_Real_Silver_Fox_Fur_Coat_Natural_Fur_Jacket_Fo_Russian_Style_Real_Silver_Fox_Fur_Coat_Natural_Fur_Jacket_Fo_605.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635259/products/Rokid_Air_AR_Smart_Glasses_120_Screen_with_1080P_OLED_Foldab_Rokid_Air_AR_Smart_Glasses_120_Screen_with_1080P_OLED_Foldab_438_9.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635252/products/Rehabilitation_Treatment_Device_Prevent_muscle_atrophy_Rehab_Rehabilitation_Treatment_Device_Prevent_muscle_atrophy_189_04.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635236/products/Real_leather_designer_women_hand_bags_handbags_for_women_lux_Real_leather_designer_women_hand_bags_handbags_for_women_lux_278_99.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635169/products/Professional_Made_Rehabilitation_Robot_Glove_Hand_Rehabilita_Professional_Made_Rehabilitation_Robot_Glove_Hand_Rehabilita_228_36.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635150/products/Portable_Excellent_Medical_Equipment_China_Digital_Hearing_A_Portable_Excellent_Medical_Equipment_China_Digital_Hearing_A_188_8.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635150/products/Portable_Excellent_Medical_Equipment_China_Digital_Hearing_A_Portable_Excellent_Medical_Equipment_China_Digital_Hearing_A_188_8.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635133/products/Perfume_777_Perfume_777_We_are_a_leading_marketing_agency_that_utilizes_over_10_year_495.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635105/products/Original_high_quality_ladies_messenger_bag_womens_luxury_han_Original_high_quality_ladies_messenger_bag_womens_luxury_han_50.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635052/products/OUMO-_11pcs_luxury_grey_squirrel_hair_green_sandalwood_handl_OUMO-_11pcs_luxury_grey_squirrel_hair_green_sandalwood_handl_493_75.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635041/products/OEM_Off_road_4x4_auto_parts_for_FJ767879_Front_Bumper_car_bu_OEM_Off_road_4x4_auto_parts_for_FJ767879_Front_Bumper_car_bu_379_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635041/products/OEM_Off_road_4x4_auto_parts_for_FJ767879_Front_Bumper_car_bu_OEM_Off_road_4x4_auto_parts_for_FJ767879_Front_Bumper_car_bu_379_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635005/products/New_arrival_tooling_leather_craft_hand_bag_for_ladies_2022_n_New_arrival_tooling_leather_craft_hand_bag_for_ladies_2022_n_341.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772635005/products/New_arrival_tooling_leather_craft_shoulder_bag_for_ladies_20_New_arrival_tooling_leather_craft_shoulder_bag_for_ladies_20_287_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634997/products/New_Style_HipHop_Iced_Out_Glasses_Men_s_Fashion_Sun_Glasses_New_Style_HipHop_Iced_Out_Glasses_Men_s_Fashion_Sun_Glasses_123_75.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634997/products/New_Style_HipHop_Iced_Out_Glasses_Men_s_Fashion_Sun_Glasses_New_Style_HipHop_Iced_Out_Glasses_Men_s_Fashion_Sun_Glasses_123_75.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634997/products/New_Style_HipHop_Iced_Out_Glasses_Men_s_Fashion_Sun_Glasses_New_Style_HipHop_Iced_Out_Glasses_Men_s_Fashion_Sun_Glasses_123_75.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634991/products/New_Trends_Jacket_Women_Wool_Coat_Belt_Long_Cashmere_And_Fur_New_Trends_Jacket_Women_Wool_Coat_Belt_Long_Cashmere_And_Fur_198.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634979/products/New_Product_Moissanite_Diamond_Buffalo_Horn_Glasses_18K_Gold_New_Product_Moissanite_Diamond_Buffalo_Horn_Glasses_18K_Gold_622_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634971/products/New_Product_High_Price_Luxury_Street_Clothing_Wind_Proof_Col_New_Product_High_Price_Luxury_Street_Clothing_Wind_Proof_Col_110.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634969/products/New_Men_s_Leather_Belts_Pin_Belts_Waistband_Waist_Strap_Genu_New_Men_s_Leather_Belts_Pin_Belts_Waistband_Waist_Strap_Genu_236_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634969/products/New_Men_s_Leather_Belts_Pin_Belts_Waistband_Waist_Strap_Genu_New_Men_s_Leather_Belts_Pin_Belts_Waistband_Waist_Strap_Genu_236_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634928/products/Necklace_18mm_Wide_trapezoidal_rhombic_baguette_S925_silver_Necklace_18mm_Wide_trapezoidal_rhombic_baguette_S925_silver_3787_3.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634927/products/Nello_Newborn_4K_pocket_Gimble_Camera_Face_Tracking_Slow_Mot_Nello_Newborn_4K_pocket_Gimble_Camera_Face_Tracking_Slow_Mot_218_9.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634925/products/Natural_cotton_skin_moisture_anti-aging_ingredient_face_mask_Natural_cotton_skin_moisture_anti-aging_ingredient_face_mask_125.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634911/products/Murtoo_Viking_Bracelets_for_Men_The_Murtoo_Viking_Bracelet_f_Murtoo_Viking_Bracelets_for_Men_24_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634886/products/Moissanite_Glasses_popular_Jewelry_Lab_Grown_Diamond_Iced_Ou_Moissanite_Glasses_popular_Jewelry_Lab_Grown_Diamond_Iced_Ou_579_8.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634892/products/Motor_spare_parts_M11_diesel_engine_forged_steel_crankshaft_Motor_spare_parts_M11_diesel_engine_forged_steel_crankshaft_650.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634883/products/Most_popular_titanium_temple_meta_optical_eyeglass_frames_lo_Most_popular_titanium_temple_meta_optical_eyeglass_frames_lo_294_8.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634878/products/Modern_studio_hotel_living_room_search_gold_white_decoration_Modern_studio_hotel_living_room_search_gold_white_decoration_216.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634878/products/Modern_studio_hotel_living_room_search_gold_white_decoration_Modern_studio_hotel_living_room_search_gold_white_decoration_216.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634855/products/Mink_Fur_Coat_Woman_Winter_Coat_Japan_Style_Long_Winter_Coat_Mink_Fur_Coat_Woman_Winter_Coat_Japan_Style_Long_Winter_Coat_944_9.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634848/products/Metal_floor_free_standing_multi-functional_sports_storage_ho_Metal_floor_free_standing_multi-functional_sports_storage_ho_43_97.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634829/products/Men_Duffel_Bag_Travel_Bags_Genuine_Leather_Luxury_FG_Antonio_Men_Duffel_Bag_Travel_Bags_Genuine_Leather_Luxury_FG_Antonio_168_99.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634814/products/Medical_Supplies_Wheelchair_Handicapped_Steel_Electric_Wheel_Medical_Supplies_Wheelchair_Handicapped_Steel_Electric_Wheel_360.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634821/products/Medical_motorised_wheelchair_with_electric_and_manual_model_Medical_motorised_wheelchair_with_electric_and_manual_model_660.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634821/products/Medical_motorised_wheelchair_with_electric_and_manual_model_Medical_motorised_wheelchair_with_electric_and_manual_model_660.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634790/products/Manufacturer_Price_Tall_Top_100_Felt_Hats_Black_Color_Rabbi_Manufacturer_Price_Tall_Top_100_Felt_Hats_Black_Color_Rabbi_156.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634789/products/Manufactory_Wholesale_Women_Leather_Jacket_Wholesale_Real_Le_Manufactory_Wholesale_Women_Leather_Jacket_Wholesale_Real_Le_286.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634781/products/Made_in_Italy_URSULA_3SB_ROCK_PYTHON_Luxury_Bag_for_party_Made_in_Italy_URSULA_3SB_ROCK_PYTHON_Luxury_Bag_for_party_756_25.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634781/products/Made_in_Italy_URSULA_3SB_ROCK_PYTHON_Luxury_Bag_for_party_Made_in_Italy_URSULA_3SB_ROCK_PYTHON_Luxury_Bag_for_party_756_25.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634768/products/Made_in_Italy_BRIGIDA_LEATHER_POWDER_PINK_Luxury_Bag_for_Cla_Made_in_Italy_BRIGIDA_LEATHER_POWDER_PINK_Luxury_Bag_for_Cla_478_13.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634768/products/Made_in_Italy_BRIGIDA_LEATHER_POWDER_PINK_Luxury_Bag_for_Cla_Made_in_Italy_BRIGIDA_LEATHER_POWDER_PINK_Luxury_Bag_for_Cla_478_13.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634768/products/Made_In_Italy_Handmade_Double_Handle_Zipper_Closure_Extracho_Made_In_Italy_Handmade_Double_Handle_Zipper_Closure_Extracho_975.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634754/products/MINI_V_BLUSH_Luxury_Made_in_Italy_blush_calf_leather_clutch_MINI_V_BLUSH_Luxury_Made_in_Italy_blush_calf_leather_clutch_208.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634754/products/MINI_V_BLUSH_Luxury_Made_in_Italy_blush_calf_leather_clutch_MINI_V_BLUSH_Luxury_Made_in_Italy_blush_calf_leather_clutch_208.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634742/products/MIGE_Manufacturer_Commercial_Furniture_3D_Adjustable_Mesh_Ch_MIGE_Manufacturer_Commercial_Furniture_3D_Adjustable_Mesh_Ch_314_6.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634732/products/M81266_NANO_NOE_BAG_M81266_NANO_NOE_BAG_We_are_a_leading_marketing_agency_that_utilizes_over_10_year_2288.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634732/products/M81266_NANO_NOE_BAG_M81266_NANO_NOE_BAG_We_are_a_leading_marketing_agency_that_utilIZES_over_10_year_2288.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634703/products/Luxury_Modern_Full_Body_Robot_AI_Smart_SL_Track_deluxe_massa_Luxury_Modern_Full_Body_Robot_AI_Smart_SL_Track_deluxe_massa_820.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634699/products/Luxury_Ladies_Hand_Bags_Branded_Quilted_Chain_Crossbody_Bags_Luxury_Ladies_Hand_Bags_Branded_Quilted_Chain_Crossbody_Bags_770.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634699/products/Luxury_Mink_Coat_Women_s_Slim_Fit_Short_Thermal_Fur_Coats_At_Luxury_Mink_Coat_Women_s_Slim_Fit_Short_Thermal_Fur_Coats_At_1007_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634699/products/Luxury_Mink_Coat_Women_s_Slim_Fit_Short_Thermal_Fur_Coats_At_Luxury_Mink_Coat_Women_s_Slim_Fit_Short_Thermal_Fur_Coats_At_1007_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634698/products/Luxury_Exotic_Skin_Bags_Genuine_Python_Leather_Handbag_for_W_Luxury_Exotic_Skin_Bags_Genuine_Python_Leather_Handbag_for_W_351.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634698/products/Luxury_Men_s_Briefcase_top_cowhide_leather_Fashion_man_offic_Luxury_Men_s_Briefcase_top_cowhide_leather_Fashion_man_offic_192_4.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634697/products/Luxury_Fashion_Pure_18K_Gold_Pawnable_Moissanite_Diamond_Rin_Luxury_Fashion_Pure_18K_Gold_Pawnable_Moissanite_Diamond_Rin_1384_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634694/products/Luxuriously_tailored_my_leather_jacket_wool_panels_real_cowh_Luxuriously_tailored_my_leather_jacket_wool_panels_real_cowh_166_32.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634694/products/Luxury18k_Gold_Glasses_Frames_Fashion_Customizable_Eyewears_Luxury18k_Gold_Glasses_Frames_Fashion_Customizable_Eyewears_1437_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634694/products/Luxury_Business_Document_Bags_Genuine_Leather_Large_Capacity_Luxury_Business_Document_Bags_Genuine_Leather_Large_Capacity_39_6.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634694/products/Luxury_Business_Document_Bags_Genuine_Leather_Large_Capacity_Luxury_Business_Document_Bags_Genuine_Leather_Large_Capacity_39_6.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634685/products/Luxurious_Baby_Stroller_3_in_1_Portable_Travel_Baby_Carriage_Luxurious_Baby_Stroller_3_in_1_Portable_Travel_Baby_Carriage_137_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634684/products/Love_at_first_sight_style_frame_Oriental_Ruyi_Aesthetics_wom_Love_at_first_sight_style_frame_Oriental_Ruyi_Aesthetics_wom_239_8.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634679/products/Light_luxury_brand_PVC_underarm_bag_for_women_large_capacity_Light_luxury_brand_PVC_underarm_bag_for_women_large_capacity_839_86.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634679/products/Light_luxury_brand_PVC_underarm_bag_for_women_large_capacity_Light_luxury_brand_PVC_underarm_bag_for_women_large_capacity_839_86.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634657/products/Lanmi_Men_s_14K18K_Yellow_White_Gold_Natural_Emerald_Ring_Sa_Lanmi_Men_s_14K18K_Yellow_White_Gold_Natural_Emerald_Ring_Sa_5116.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634647/products/Ladybug_Flower_Clip-On_Earrings_Brilliantly_bejeweled_and_tr_Ladybug_Flower_Clip-On_Earrings_266.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634647/products/Ladybug_Flower_Clip-On_Earrings_Brilliantly_bejeweled_and_tr_Ladybug_Flower_Clip-On_Earrings_266.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634605/products/JTLD_High_Performance_Auto_Parts_SUS304_Muffler_Exhaust_for_JTLD_High_Performance_Auto_Parts_SUS304_Muffler_Exhaust_for_1300.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634600/products/Italy_2022_Orange_Cotton_Lining_Patent_Leather_Iridescent_St_Italy_2022_Orange_Cotton_Lining_Patent_Leather_Iridescent_St_312.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634563/products/Interactive_Workout_Smart_Home_Full_Size_Body_Smart_Fitness_Interactive_Workout_Smart_Home_Full_Size_Body_Smart_Fitness_528_44.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634555/products/Indoor_Decoration_Light_Wood_Fish_Project_Large_Hotel_Lobby_Indoor_Decoration_Light_Wood_Fish_Project_Large_Hotel_Lobby_55.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634549/products/IGI_Certified_14-2_Carat_Lab_Grown_Diamond_Stud_Earrings_in_IGI_Certified_14-2_Carat_Lab_Grown_Diamond_Stud_Earrings_in_2420.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634515/products/Hot_sale_sac_a_main_hand_bag_women_custom_tote_bag_canvas_to_Hot_sale_sac_a_main_hand_bag_women_custom_tote_bag_canvas_to_364.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634515/products/Hot_sale_sac_a_main_hand_bag_women_custom_tote_bag_canvas_to_Hot_sale_sac_a_main_hand_bag_women_custom_tote_bag_canvas_to_364.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634499/products/Hot_sale_home_furniture_saving_space_wood_wall_beds_murphy_b_Hot_sale_home_furniture_saving_space_wood_wall_beds_murphy_b_859_1.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634499/products/Hot_sale_home_furniture_saving_space_wood_wall_beds_murphy_b_Hot_sale_home_furniture_saving_space_wood_wall_beds_murphy_b_859_1.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634501/products/Hot_Wholesale_Winter_Female_Clothes_Coat_Ladies_Luxury_Racco_Hot_Wholesale_Winter_Female_Clothes_Coat_Ladies_Luxury_Racco_425_7.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634487/products/Hot_Selling_Best_Swimming_Goggles_Sport_Eyewear_Racing_Smart_Hot_Selling_Best_Swimming_Goggles_Sport_Eyewear_Racing_Smart_328_9.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634486/products/Hot_Selling_2023_Evel_Knievel_Tribute_Royal_Blue_Leather_Jac_Hot_Selling_2023_Evel_Knievel_Tribute_Royal_Blue_Leather_Jac_234.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634472/products/Hot_Mom_360_Rotation_Baby_Stroller_Wheelchair_Accessories_3_Hot_Mom_360_Rotation_Baby_Stroller_Wheelchair_Accessories_3_536_25.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634451/products/Hip_hop_glasses_inlaid_with_gem_metal_frame_wooden_red_leg_g_Hip_hop_glasses_inlaid_with_gem_metal_frame_wooden_red_leg_g_182_64.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634438/products/High_quality_handbag_oem_womens_genuine_leather_branded_bag_High_quality_handbag_oem_womens_genuine_leather_branded_bag_605.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634440/products/High_quality_light_luxury_fox_fur_handbag_winter_color_fox_f_High_quality_light_luxury_fox_fur_handbag_winter_color_fox_f_453_7.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634440/products/High_quality_light_luxury_fox_fur_handbag_winter_color_fox_f_High_quality_light_luxury_fox_fur_handbag_winter_color_fox_f_453_7.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634433/products/High_quality_Luxury_Ladies_Winter_Fashion_bags_New_Design_Ju_High_quality_Luxury_Ladies_Winter_Fashion_bags_New_Design_Ju_234.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634433/products/High_quality_Luxury_Ladies_Winter_Fashion_bags_New_Design_Ju_High_quality_Luxury_Ladies_Winter_Fashion_bags_New_Design_Ju_234.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634433/products/High_quality_Luxury_Ladies_Winter_Fashion_bags_New_Design_Ju_High_quality_Luxury_Ladies_Winter_Fashion_bags_New_Design_Ju_234.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634433/products/High_quality_Soft_Touch_Rubber_beach_volleyball_of_High_qual_High_quality_Soft_Touch_Rubber_beach_volleyball_of_37_95.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634416/products/High_Quality_Tote_Bag_Women_Hand_Bags_Real_Fox_Fur_Shoulder_High_Quality_Tote_Bag_Women_Hand_Bags_Real_Fox_Fur_Shoulder_275.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634417/products/High_Quality_Promotion_Women_s_Down_Coats_Goose_Down_Coats_W_High_Quality_Promotion_Women_s_Down_Coats_Goose_Down_Coats_W_344_59.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634417/products/High_Quality_Promotion_Women_s_Down_Coats_Goose_Down_Coats_W_High_Quality_Promotion_Women_s_Down_Coats_Goose_Down_Coats_W_344_59.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634417/products/High_Quality_Promotion_Women_s_Down_Coats_Goose_Down_Coats_W_High_Quality_Promotion_Women_s_Down_Coats_Goose_Down_Coats_W_344_59.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634417/products/High_Quality_Promotion_Women_s_Down_Coats_Goose_Down_Coats_W_High_Quality_Promotion_Women_s_Down_Coats_Goose_Down_Coats_W_344_59.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634339/products/Handbag_Bags_For_Luxury_Ladies_Tote_Bag_Women_made_in_Italy_Handbag_Bags_For_Luxury_Ladies_Tote_Bag_Women_made_in_Italy_2032_29.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634334/products/Hanke_New_arrival_waterproof_fabric_trolley_suitcase_set_Cus_Hanke_New_arrival_waterproof_fabric_trolley_suitcase_set_Cus_39_81.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634333/products/Handwork_leather_tote_bag_lady_s_satchel_bags_Handwork_leath_Handwork_leather_tote_bag_lady_s_satchel_bags_765_6.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634333/products/Hand_Crafted_AAA_Rubellite_Tourmaline_Long_Layering_Necklac_Hand_Crafted_AAA_Rubellite_Tourmaline_Long_Layering_Necklac_5554_74.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634328/products/HUMERPAUL_Dropship_Wholesale_Vintage_Crazy_Horse_Leather_Bri_HUMERPAUL_Dropship_Wholesale_Vintage_Crazy_Horse_Leather_Bri_58_29.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634328/products/HUMERPAUL_Dropship_Wholesale_Vintage_Crazy_Horse_Leather_Bri_HUMERPAUL_Dropship_Wholesale_Vintage_Crazy_Horse_Leather_Bri_58_29.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634328/products/Hand-embroidered_fashion_British_casual_ladiesmen_s_leather_Hand-embroidered_fashion_British_casual_ladiesmen_s_leather_1014.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634318/products/HUAWEI_X_Gentle_M_smart_Eyewear_SMART_JACKBYE-01_smart_glass_HUAWEI_X_Gentle_M_smart_Eyewear_SMART_JACKBYE-01_smart_glass_404_8.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634318/products/HUAWEI_X_Gentle_M_smart_Eyewear_SMART_JACKBYE-01_smart_glass_HUAWEI_X_Gentle_M_smart_Eyewear_SMART_JACKBYE-01_smart_glass_404_8.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634303/products/HD30-089_Trending_Products_Women_Bag_Handbag_Crossbody_Bags_HD30-089_Trending_Products_Women_Bag_Handbag_Crossbody_Bags_1765_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634287/products/Guangdong_Manufacturer_Wholesale_Modern_7ft_8ft_PVC_Pre_Lit_Guangdong_Manufacturer_Wholesale_Modern_7ft_8ft_PVC_Pre_Lit_109_99.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634295/products/Grandtime_2021_Bestselling_Wireless_2G3G4G_Dual_mic_Video_Re_Grandtime_2021_Bestselling_Wireless_2G3G4G_Dual_mic_Video_Re_1034.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634295/products/Grandtime_2021_Bestselling_Wireless_2G3G4G_Dual_mic_Video_Re_Grandtime_2021_Bestselling_Wireless_2G3G4G_Dual_mic_Video_Re_1034.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634273/products/Gogloo_HD_sunglasses_camera_with_remote_control_mini_cams_vi_Gogloo_HD_sunglasses_camera_with_remote_control_mini_cams_vi_132.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634265/products/Giant_Inflatable_Human_Sports_Football_Dartboard_Soccer_Dart_Giant_Inflatable_Human_Sports_Football_Dartboard_Soccer_Dart_988_9.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634265/products/Giant_Inflatable_Human_Sports_Football_Dartboard_Soccer_Dart_Giant_Inflatable_Human_Sports_Football_Dartboard_Soccer_Dart_988_9.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634251/products/Garment_factory_Custom_men_chenille_patch_Embroidery_Basebal_Garment_factory_Custom_men_chenille_patch_Embroidery_Basebal_123_2.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634251/products/Garment_factory_Custom_men_chenille_patch_Embroidery_Basebal_Garment_factory_Custom_men_chenille_patch_Embroidery_Basebal_123_2.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634239/products/Fur_Over_Coat_Lady_Winter_Coat_Woman_Winter_Real_Fur_Coat_Fo_Fur_Over_Coat_Lady_Winter_Coat_Woman_Winter_Real_Fur_Coat_Fo_253.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634234/products/Full_Set_of_seven_Eau_de_pafums_100_ml_Mediterranee_Artistic_Full_Set_of_seven_Eau_de_pafums_100_ml_Mediterranee_Artistic_420.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634230/products/GIOVANNI_GUIDI_Fashion_Luxury_Pu_Leather_Ladies_Shoulder_Bag_GIOVANNI_GUIDI_Fashion_Luxury_Pu_Leather_Ladies_Shoulder_Bag_168_87.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634230/products/Full_Set_of_eighteen_Eau_de_pafums_and_Extrait_de_parfums_10_Full_Set_of_eighteen_Eau_de_pafums_and_Extrait_de_parfums_10_1670_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634230/products/Full_Set_of_eighteen_Eau_de_pafums_and_Extrait_de_parfums_10_Full_Set_of_eighteen_Eau_de_pafums_and_Extrait_de_parfums_10_1670_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634223/products/Freestanding_Bathtub_Acrylic_Baby_Spa_Swimming_Floating_Pool_Freestanding_Bathtub_Acrylic_Baby_Spa_Swimming_Floating_Pool_810.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634216/products/Frameless_Stand_dressing_mirror_with_led_bulbs_amazon_prime_Frameless_Stand_dressing_mirror_with_led_bulbs_amazon_prime_188_74.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634151/products/Fashion_wooden_handbag_single_shoulder_bag_dog_tooth_crossbo_Fashion_wooden_handbag_single_shoulder_bag_dog_tooth_crossbo_208.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634151/products/Fashion_wooden_handbag_single_shoulder_bag_dog_tooth_crossbo_Fashion_wooden_handbag_single_shoulder_bag_dog_tooth_crossbo_208.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634143/products/Fashion_Women_Tote_Bag_Daily_Genuine_Leather_Handbag_Shoulde_Fashion_Women_Tote_Bag_Daily_Genuine_Leather_Handbag_Shoulde_227_37.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634143/products/Fashion_Women_Tote_Bag_Daily_Genuine_Leather_Handbag_Shoulde_Fashion_Women_Tote_Bag_Daily_Genuine_Leather_Handbag_Shoulde_227_37.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634140/products/Fashion_Luxury_Handbags_Women_Womens_Bag_Branded_Bags_Wholes_Fashion_Luxury_Handbags_Women_Womens_Bag_Branded_Bags_Wholes_225_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634140/products/Fashion_Luxury_Handbags_Women_Womens_Bag_Branded_Bags_Wholes_Fashion_Luxury_Handbags_Women_Womens_Bag_Branded_Bags_Wholes_225_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634139/products/Fashion_Leather_Belts_Customized_Logo_With_Copper_Buckle_Cla_Fashion_Leather_Belts_Customized_Logo_With_Copper_Buckle_Cla_88.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634139/products/Fashion_Luxury_Quilted_Handbag_Sets_Crossbody_Handbags_Bags_Fashion_Luxury_Quilted_Handbag_Sets_Crossbody_Handbags_Bags_251_9.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634136/products/Fashion_Hat_Ladies_Oversize_Straw_Boater_Extra_Large_Brim_W",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634135/products/Fashion_Handbag_Canvas_Bag_Women_s_Portable_Platinum_Cowhide_Fashion_Handbag_Canvas_Bag_Women_s_Portable_Platinum_Cowhide_41_8.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634135/products/Fashion_Designer_Woven_Cross_Armpit_Hobo_Knot_Bags_Ladies_Ha_Fashion_Designer_Woven_Cross_Armpit_Hobo_Knot_Bags_Ladies_Ha_290_79.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634132/products/Fall_2022_V-Neck_Contrast_Patchwork_Panel_Fashion_Women_s_Sk_Fall_2022_V-Neck_Contrast_Patchwork_Panel_Fashion_Women_s_Sk_159_71.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634131/products/Fashion_18K_Gold_Half_Glasses_Men_s_Business_Casual_Eyewear_Fashion_18K_Gold_Half_Glasses_Men_s_Business_Casual_Eyewear_5875.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634131/products/Factory_wholesale_real_fox_fur_big_fur_collarfur_cloth_Facto_Factory_wholesale_real_fox_fur_big_fur_collarfur_cloth_144.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634128/products/Factory_outlet_Professional_Hand_made_Clap_ice_skate_shoes_i_Factory_outlet_Professional_Hand_made_Clap_ice_skate_shoes_i_276_75.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634131/products/Factory_wholesale_italian_women_real_fox_fur_coats_Factory_w_Factory_wholesale_italian_women_real_fox_fur_coats_313_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634131/products/Factory_wholesale_italian_women_real_fox_fur_coats_Factory_w_Factory_wholesale_italian_women_real_fox_fur_coats_313_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634123/products/Factory_Supply_Dumbbell_Commercial_Gym_Equipment_Silver_Spor_Factory_Supply_Dumbbell_Commercial_Gym_Equipment_Silver_Spor_90_2.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634122/products/Factory_Wholesale_18K_Gold_Metal_diamond_glasses_Frames_EH00_Factory_Wholesale_18K_Gold_Metal_diamond_glasses_Frames_EH00_7290.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634097/products/Factory_Custom_Branded_Fashionable_Racing_Sport_Eyewear_Anti_Factory_Custom_Branded_Fashionable_Racing_Sport_Eyewear_Anti_328_9.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634097/products/Factory_Custom_Branded_Fashionable_Racing_Sport_Eyewear_Anti_Factory_Custom_Branded_Fashionable_Racing_Sport_Eyewear_Anti_328_9.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634102/products/Factory_Price_Auto_Parts_For_Lifan_320_Spare_Parts_Factory_P_Factory_Price_Auto_Parts_For_Lifan_320_Spare_Parts_390.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634096/products/Factory_Custom_Wholesale_Real_Men_Fluffy_Fur_Jackets_Winter_Factory_Custom_Wholesale_Real_Men_Fluffy_Fur_Jackets_Winter_748.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634096/products/Factory_Custom_Wholesale_Real_Men_Fluffy_Fur_Jackets_Winter_Factory_Custom_Wholesale_Real_Men_Fluffy_Fur_Jackets_Winter_748.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634077/products/Elegant_genuine_fashionable_leather_luxury_women_bags_handba_Elegant_genuine_fashionable_leather_luxury_women_bags_handba_825.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772634077/products/Enduro_boots_for_men_motocross_scoyco_moto_boots_for_women_r_Enduro_boots_for_men_motocross_scoyco_moto_boots_for_women_r_234_46.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633993/products/Designer_Cheap_Ladies_Grid_Tote_Bags_Luxury_Women_Bags_Handb_Designer_Cheap_Ladies_Grid_Tote_Bags_Luxury_Women_Bags_Handb_735.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633993/products/Designer_Cheap_Ladies_Grid_Tote_Bags_Luxury_Women_Bags_Handb_Designer_Cheap_Ladies_Grid_Tote_Bags_Luxury_Women_Bags_Handb_735.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633946/products/Custom_Travelling_Bags_Foldable_Carry_On_Ride_On_Children_Ki_Custom_Travelling_Bags_Foldable_Carry_On_Ride_On_Children_Ki_85_36.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633944/products/Custom_Long_Sleeves_Fashion_Women_Fluffy_Fur_Jacket_Winter_R_Custom_Long_Sleeves_Fashion_Women_Fluffy_Fur_Jacket_Winter_R_448_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633939/products/Custom_Genuine_Leather_Travel_Weekender_Overnight_Duffel_Bag_Custom_Genuine_Leather_Travel_Weekender_Overnight_Duffel_Bag_50_96.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633937/products/Custom_Designs_Chinese_style_18K_Real_Gold_With_Lab_grown_HP_Custom_Designs_Chinese_style_18K_Real_Gold_With_Lab_grown_HP_2275.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633939/products/Custom_Fitness_Equipment_Gymnastics_Water_Sports_Floating_In_Custom_Fitness_Equipment_Gymnastics_Water_Sports_Floating_In_116_82.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633937/products/Custom_Designs_Chinese_style_18K_Real_Gold_With_Lab_grown_HP_Custom_Designs_Chinese_style_18K_Real_Gold_With_Lab_grown_HP_2275.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633935/products/Crocodile_skin_women_2022_new_summer_leather_senior_sense_ch_Crocodile_skin_women_2022_new_summer_leather_senior_sense_ch_297.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633935/products/Cryopush_dual_cold_compression_therapy_system_lower_body_ful_Cryopush_dual_cold_compression_therapy_system_lower_body_ful_487_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633935/products/Creative_Leisure_Armrest_Single_Sofa_Chair_Furniture_Comfort_Creative_Leisure_Armrest_Single_Sofa_Chair_Furniture_Comfort_368_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633933/products/Cts_Black_Diamond_Jewelry_Set_This_resplendent_Black_Diamond_Cts_Black_Diamond_Jewelry_Set_2898_99.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633931/products/Contact_s_vintage_crazy_horse_leather_9_7_inch_pad_genuine_l_We_are_a_leading_marketing_agency_that_utilIZES_over_10_year_Contact_s_vintage_crazy_horse_leather_9_7_inch_pad_genuine_l.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633931/products/Contact_s_vintage_crazy_horse_leather_9_7_inch_pad_genuine_l_We_are_a_leading_marketing_agency_that_utilIZES_over_10_year_Contact_s_vintage_crazy_horse_leather_9_7_inch_pad_genuine_l.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633924/products/Competitive_Price_Sun_Protection_Hat_Outdoor_Camping_Riding_Competitive_Price_Sun_Protection_Hat_Outdoor_Camping_Riding_299_94.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633919/products/Comfort_renowned_high_quality_custom_bags_women_handbags_lad_Comfort_renowned_high_quality_custom_bags_women_handbags_lad_1662_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633919/products/Comfort_renowned_high_quality_custom_bags_women_handbags_lad_Comfort_renowned_high_quality_custom_bags_women_handbags_lad_1662_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633887/products/Cheerleading_Pad_Bonding_Foam_Roll_Training_6_X_42_Carpet_B_Cheerleading_Pad_Bonding_Foam_Roll_Training_6_X_42_Carpet_B_550.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633903/products/China_Factory_Price_wholesale_auto_bumper_for_volvo_xc90_20_China_Factory_Price_wholesale_auto_bumper_for_volvo_xc90_20_373_75.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633891/products/Cheap_Private_Label_Axe_Men_Body_Mist_Deodorant_Charm_Men_Pe_Cheap_Private_Label_Axe_Men_Body_Mist_Deodorant_Charm_Men_Pe_1575_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633891/products/Cheap_Private_Label_Axe_Men_Body_Mist_Deodorant_Charm_Men_Pe_Cheap_Private_Label_Axe_Men_Body_Mist_Deodorant_Charm_Men_Pe_1575_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633846/products/Chanel_Black_Code_Coco_Black_Diamond_Dial_Ladies_Steel_and_C_Chanel_Black_Code_Coco_Black_Diamond_Dial_Ladies_Steel_and_C_5472.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633839/products/Ceramic_Flower_Bouquet_3_Heads_Small_Wrought_Iron_Pendant_La_Ceramic_Flower_Bouquet_3_Heads_Small_Wrought_Iron_Pendant_La_152_9.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633837/products/Chain_Crossbody_Shoulder_Bag_Leopard_Real_Mink_Fur_Hand_Bags_Chain_Crossbody_Shoulder_Bag_Leopard_Real_Mink_Fur_Hand_Bags_275.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633832/products/Car_parts_of_auto_steering_system_electric_power_steering_co_Car_parts_of_auto_steering_system_electric_power_steering_co_198.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633832/products/Car_parts_of_auto_steering_system_electric_power_steering_co_Car_parts_of_auto_steering_system_electric_power_steering_co_198.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633828/products/CNTECH_Factory_2600W_Multifunction_Electric_Carpet_Mattress_CNTECH_Factory_2600W_Multifunction_Electric_Carpet_Mattress_239_8.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633827/products/Camera_on_Glasses_1080P_Video_Sunglasses_with_Camera_Wide_An_Camera_on_Glasses_1080P_Video_Sunglasses_with_Camera_Wide_An_132.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633822/products/CBD_cream_Face_cream_Concentrate_Brightening_Anti_aging_Wri_CBD_cream_Face_cream_Concentrate_Brightening_Anti_aging_Wri_1860.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633822/products/Bulova_Men_s_Classic_Surveyor_2-Hand_DayDate_Quartz_Watch_L_Bulova_Men_s_Classic_Surveyor_2-Hand_DayDate_Quartz_Watch_L_262.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633275/products/Brand_bags_women_handbags_luxury_crocodile_leather_women_s_b_Brand_bags_women_handbags_luxury_crocodile_leather_women_s_b_495.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633274/products/Brand_New_Mini_Designer_women_s_bags_For_Lady_Crossbody_Bag_Brand_New_Mini_Designer_women_s_bags_For_Lady_Crossbody_Bag_325.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633274/products/Brand_New_Mini_Designer_women_s_bags_For_Lady_Crossbody_Bag_Brand_New_Mini_Designer_women_s_bags_For_Lady_Crossbody_Bag_325.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633261/products/Blemish_Elimination_Skin_Care_Whitening_Facial_Mask_with_Nat_Blemish_Elimination_Skin_Care_Whitening_Facial_Mask_with_Nat_62_81.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633260/products/Borregls_S925_Sterling_Silver_Moissanite_Diamonds_Buffalo_Ho_Borregls_S925_Sterling_Silver_Moissanite_Diamonds_Buffalo_Ho_385.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633186/products/Best_herbal_medicine_cutter_herbs_cutting_machine_herb_slici_Best_herbal_medicine_cutter_herbs_cutting_machine_herb_slici_533_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633186/products/Best_herbal_medicine_cutter_herbs_cutting_machine_herb_slici_Best_herbal_medicine_cutter_herbs_cutting_machine_herb_slici_533_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633146/products/Bathroom_Electric_Toilet_Lift_health_care_supplies_products_Bathroom_Electric_Toilet_Lift_health_care_supplies_products_755_64.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633100/products/Baby_New_Product_Hot_Selling_Good_Quality_New_Arrivals_Baby_Baby_New_Product_Hot_Selling_Good_Quality_New_Arrivals_Baby_78.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633104/products/Bamboo_Handle_Handbags_For_Women_Luxury_Designer_Tote_Handba_Bamboo_Handle_Handbags_For_Women_Luxury_Designer_Tote_Handba_118_8.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633072/products/Auto_Spare_Parts_for_CHERY_all_series_Arrizo_3_Arrizo_5Arriz_Auto_Spare_Parts_for_CHERY_all_series_Arrizo_3_Arrizo_5Arriz_550.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633071/products/Auto_parts_For_Encore_16-18_Front_Bumper_Assembly_Fit_For_Bu_Auto_parts_For_Encore_16-18_Front_Bumper_Assembly_Fit_For_Bu_132.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633071/products/Auto_Hot_Sale_Xenon_Version_Headlight_For_VOLVO_XC60_S60_Spa_Auto_Hot_Sale_Xenon_Version_Headlight_For_VOLVO_XC60_S60_Spa_438_75.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633067/products/Auto_Engine_Parts_2AZ_FE_balance_shaft_for_Toyota_Camry_High_Auto_Engine_Parts_2AZ_FE_balance_shaft_for_Toyota_Camry_High_218_93.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633070/products/Auto_Parts_Accessories_Snorkel_LowHigh_Mount_for_Jeep_Wrangl_Auto_Parts_Accessories_Snorkel_LowHigh_Mount_for_Jeep_Wrangl_227_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633070/products/Auto_Parts_Accessories_Snorkel_LowHigh_Mount_for_Jeep_Wrangl_Auto_Parts_Accessories_Snorkel_LowHigh_Mount_for_Jeep_Wrangl_227_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633054/products/ActEarlier_custom_logo_design_print_grain_surface_ActEarlier_ActEarlier_custom_logo_design_print_grain_surface_45_1.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772633003/products/APP_Sports_Training_Connected_Bluetooth_Operation_Agile_Reac_APP_Sports_Training_Connected_Bluetooth_Operation_Agile_Reac_240_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632970/products/925_Sterling_Silver_Green_Enamel_Belt_Buckle_Square_Shape_Cr_925_Sterling_Silver_Green_Enamel_Belt_Buckle_Square_Shape_Cr_181_5.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632963/products/80L_Professional_Mountaineering_Military_Back_Pack_80L_Profe_80L_Professional_Mountaineering_Military_Back_Pack_36_21.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632951/products/7-speed_electric_mountain_bike_frame_500_750W_48V_fat_tire_7-speed_electric_mountain_bike_frame_500_750W_48V_fat_tire_1077_7.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632946/products/60_cm_high_landscape_Baby_Cart_Sitting_Lying_Folding_baby_st_60_cm_high_landscape_Baby_Cart_Sitting_Lying_Folding_baby_st_217_8.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632754/products/2023_Luxury_Square_Fur_Bag_Genuine_Mink_Fur_Handbags_for_Wom_2023_Luxury_Square_Fur_Bag_Genuine_Mink_Fur_Handbags_for_Wom_167_7.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632731/products/2023_Luxury_Designer_Fashion_Leather_PursesHandbags_Famous_B_2023_Luxury_Designer_Fashion_Leather_PursesHandbags_Famous_B_208.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632718/products/2022_winter_new_fashion_trend_imported_whole_skin_fox_fur_gr_2022_winter_new_fashion_trend_imported_whole_skin_fox_fur_gr_735.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632712/products/2022_hot_sale_smart_WIFI_Version_Portable_LED_Backpack_Mobil_2022_hot_sale_smart_WIFI_Version_Portable_LED_Backpack_Mobil_48_4.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632712/products/2022_hot_sale_smart_WIFI_Version_Portable_LED_Backpack_Mobil_2022_hot_sale_smart_WIFI_Version_Portable_LED_Backpack_Mobil_48_4.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632707/products/2022_autumn_winter_new_cashmere_sweater_women_pure_cashmere_2022_autumn_winter_new_cashmere_sweater_women_pure_cashmere_119_13.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632701/products/2022_Wholesale_Hot_Selling_Ladies_Mini_Bags_Top_Quality_Tren_2022_Wholesale_Hot_Selling_Ladies_Mini_Bags_Top_Quality_Tren_893_2.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632701/products/2022_Wholesale_Hot_Selling_Ladies_Mini_Bags_Top_Quality_Tren_2022_Wholesale_Hot_Selling_Ladies_Mini_Bags_Top_Quality_Tren_893_2.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632265/products/2022_Nile_crocodile_leather_Himalaya_white_high-end_hand-sti_2022_Nile_crocodile_leather_Himalaya_white_high-end_hand-sti_1558_7.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632265/products/2022_Nile_crocodile_leather_Himalaya_white_high-end_hand-sti_2022_Nile_crocodile_leather_Himalaya_white_high-end_hand-sti_1558_7.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632225/products/2022_Autumn_New_Raccon_Fur_Sleeve_Collar_Real_Leather_Jacket_2022_Autumn_New_Raccon_Fur_Sleeve_Collar_Real_Leather_Jacket_220.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632225/products/2022_Bio_resonance_8d_nls_body_health_analyzer_for_health_de_2022_Bio_resonance_8d_nls_body_health_analyzer_for_health_de_484_25.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632225/products/2022_Custom_Woman_Real_Fur_Jacket_For_Woman_Trendy_With_Shor_2022_Custom_Woman_Real_Fur_Jacket_For_Woman_Trendy_With_Shor_750.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632204/products/2021_Natural_Jade_Bracelet_Bangle_Emerald_Jadeite_Bangles_Br_2021_Natural_Jade_Bracelet_Bangle_Emerald_Jadeite_Bangles_Br_2444.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632185/products/2021_Hot_Selling_Fashion_Audio_Smart_Men_Sunglasses_2021_Hot_2021_Hot_Selling_Fashion_Audio_Smart_Men_Sunglasses_3520.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632185/products/2021Women_s_luxury_handbag_first_lady_bag_raw_boa_skin_high_2021Women_s_luxury_handbag_first_lady_bag_raw_boa_skin_high_550.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632143/products/11_Fashion_Designer_Famous_Brands_Crossbody_Bags_Women_Luxur_11_Fashion_Designer_Famous_Brands_Crossbody_Bags_Women_Luxur_49_5.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772632126/products/100ML_NOSTALGIA_TIMELESS_ORIGINAL_PERFUME_BY_LORIS_BRAND_FOR__100ML_NOSTALGIA_TIMELESS_ORIGINAL_PERFUME_BY_LORIS_BRAND_FOR__%C2%A3_3250.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772365148/products/2022_Leeffon_Stylish_Lipstick_Evening_Bags_Luxury_Ladies_Clu_2022_Leeffon_Stylish_Lipstick_Evening_Bags_Luxury_Ladies_Clu_132_opyllj.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772630912/products/products/0_10_ct_Mens_Round_Cut_Diamond_Wedding_Band_Ring_Present_hi_Present_him_with_a_diamond_surprise_on_that_special_day_with_0_10_ct_Mens_Round_Cut_Diamond_Wedding_Band_Ring.jpg",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772365047/products/yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_yujiang_C_yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_40_15_gsf72v.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772365047/products/yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_yujiang_C_yujiang_Car_Exterior_Decoration_Rear_Guard_Protect_40_15_gsf72v.png",
  "https://res.cloudinary.com/dycytqdfj/image/upload/v1772365024/products/Xinzhilian_Colombia_Private_Label_Green_Cropped_270Gsm_Scrub_Xinzhilian_Colombia_Private_Label_Green_Cropped_270Gsm_Scrub_155_21_shonvq.jpg"
];

/* Shuffle the URLs at runtime so pages don't show grouped identical products */
function shuffleArray(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/* Build product objects with name and a short description */
const productsFromUrls = (urls) =>
  urls.map((url, idx) => {
    const name = friendlyNameFromUrl(url);
    const lower = name.toLowerCase();
    const desc = (() => {
      if (lower.includes("boot")) return "Durable and stylish — great for outdoor and winter wear.";
      if (lower.includes("sneaker") || lower.includes("sneakers") || lower.includes("nike") || lower.includes("yeezy"))
        return "Comfortable sneaker for everyday wear and sports.";
      if (lower.includes("slipper") || lower.includes("loafer")) return "Casual and comfortable slip-on — great for home and casual outings.";
      if (lower.includes("oxford") || lower.includes("leather")) return "Premium leather craftsmanship for formal occasions.";
      if (lower.includes("heel") || lower.includes("pump")) return "Elevate your outfit with these stylish heels.";
      if (lower.includes("ice skate") || lower.includes("skate")) return "Specialized skate shoes for performance and style.";
      return "High quality shoes with excellent comfort and design.";
    })();
    return { id: idx + 1, name, desc, img: url };
  });

export default function Shoes() {
  // Shuffle once on component mount (keeps behavior same as Apparel & Accessories)
  const shuffledUrls = useMemo(() => shuffleArray(productUrls), []);
  const products = useMemo(() => productsFromUrls(shuffledUrls), [shuffledUrls]);

  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 8; // exactly 8 products per page
  const total = products.length;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));

  const pageProducts = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    return products.slice(start, start + pageSize);
  }, [currentPage, products]);

  const goTo = (page) => {
    const p = Math.max(1, Math.min(totalPages, page));
    setCurrentPage(p);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const pageNumbers = useMemo(() => {
    const maxButtons = 7;
    if (totalPages <= maxButtons) return Array.from({ length: totalPages }, (_, i) => i + 1);
    const half = Math.floor(maxButtons / 2);
    let start = Math.max(1, currentPage - half);
    let end = start + maxButtons - 1;
    if (end > totalPages) {
      end = totalPages;
      start = end - maxButtons + 1;
    }
    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  }, [currentPage, totalPages]);

  return (
    <div className="shoes-page">
      {/* Inject a small style override so we don't have to change Shoes.css */}
      <style>{`
        /* Ensure hero image never grows past a reasonable height on large screens */
        .shoes-hero .shoes-hero-left .shoes-hero-img {
          width: 100%;
          height: 100%;
          object-fit: cover; /* keep visual fill but constrained by max-height below */
          max-height: 60vh; /* default cap relative to viewport */
        }

        /* On larger desktop screens clamp to a fixed pixel max so it doesn't push layout */
        @media (min-width: 1200px) {
          .shoes-hero .shoes-hero-left .shoes-hero-img {
            max-height: 520px; /* adjust as needed to match the marked line */
          }
        }

        /* Make product images fit into their product card boxes without increasing card size.
           We use contain so the full image is visible and not cropped; the card size remains controlled by existing CSS. */
        .products-grid .product-card .product-media img {
          width: 100%;
          height: 100%;
          object-fit: contain;
          display: block;
        }

        /* Do not modify the small mini thumbnails (mini-1, mini-2) as requested - they remain controlled by Shoes.css */
      `}</style>

      {/* HERO */}
      <section
        className="shoes-hero"
        role="region"
        aria-label="Shoes hero"
      >
        <div className="shoes-hero-inner">
          <div className="shoes-hero-left" aria-hidden="true">
            {/* Use imported Shoes.png as a contained <img> so it stays inside the left card */}
            <img
              src={ShoesHero}
              alt="Shoes hero"
              className="shoes-hero-img"
              // Inline fallback / extra safety to cap height and preserve fit if global CSS overrides are present
              style={{ maxHeight: "60vh", width: "100%", objectFit: "cover" }}
            />
          </div>

          <div className="shoes-hero-right">
            <div className="shoes-hero-right-inner">
              <div className="shoes-kicker">ACCESSORIES</div>
              <h1 className="shoes-hero-title">Authentic accessories from the best brands.</h1>
              <p className="shoes-hero-sub">Updated weekly with new flash sales from some of the world's best brands.</p>
            </div>

            <div className="shoes-hero-mini">
              {/* small thumbnails on the bottom-right as seen in screenshot */}
              <img src={pageProducts[0]?.img || ""} alt="" className="mini-1" />
              <img src={pageProducts[1]?.img || ""} alt="" className="mini-2" />
            </div>
          </div>
        </div>
      </section>

      {/* product count and sort row */}
      <div className="shoes-toolbar">
        <div className="shoes-count">{total} Products Found</div>
        <div className="shoes-sort">
          <label htmlFor="sort">Sort by</label>
          <select id="sort" name="sort" defaultValue="recommended">
            <option value="recommended">Recommended</option>
            <option value="new">Newest</option>
            <option value="price-asc">Price: Low to High</option>
            <option value="price-desc">Price: High to Low</option>
          </select>
        </div>
      </div>

      {/* PRODUCTS GRID */}
      <main className="shoes-products" role="main">
        <div className="products-grid" aria-live="polite">
          {pageProducts.map((p) => (
            <a
              key={p.id}
              href={`/shoes/${p.id}`}
              className="product-card"
              title={`${p.name} — ${p.desc}`}
              rel="noopener"
            >
              <div className="product-media">
                {/* Product images: use object-fit contain so they don't overflow or get cropped;
                    card sizes remain controlled by Shoes.css */}
                <img
                  src={p.img}
                  alt={p.name}
                  loading="lazy"
                  style={{ width: "100%", height: "100%", objectFit: "contain", display: "block" }}
                />
              </div>
              <div className="product-body">
                <h3 className="product-name">{p.name}</h3>
                <p className="product-desc">{p.desc}</p>
                <div className="product-actions">
                  <button type="button" className="btn-quick">Quick View</button>
                </div>
              </div>
            </a>
          ))}
        </div>

        {/* PAGINATION */}
        <nav className="shoes-pagination" aria-label="Pagination">
          <button onClick={() => goTo(currentPage - 1)} disabled={currentPage === 1} className="pg-btn">
            Prev
          </button>

          {pageNumbers[0] > 1 && (
            <>
              <button onClick={() => goTo(1)} className="pg-btn">1</button>
              {pageNumbers[0] > 2 && <span className="pg-ellipsis">…</span>}
            </>
          )}

          {pageNumbers.map((n) => (
            <button
              key={n}
              onClick={() => goTo(n)}
              className={`pg-btn ${n === currentPage ? "active" : ""}`}
              aria-current={n === currentPage ? "page" : undefined}
            >
              {n}
            </button>
          ))}

          {pageNumbers[pageNumbers.length - 1] < totalPages && (
            <>
              {pageNumbers[pageNumbers.length - 1] < totalPages - 1 && <span className="pg-ellipsis">…</span>}
              <button onClick={() => goTo(totalPages)} className="pg-btn">{totalPages}</button>
            </>
          )}

          <button onClick={() => goTo(currentPage + 1)} disabled={currentPage === totalPages} className="pg-btn">
            Next
          </button>
        </nav>
      </main>
    </div>
  );
}